### PR TITLE
feat(Android): added navigationBarTranslucent option

### PR DESCRIPTION
**Pull request by alduzy**
**Motivation**

This PR intents to enable navigation bar translucency control. You can find more about this feature [here](https://github.com/software-mansion/react-native-screens/pull/2152)

**Test plan**

Play around with following screen options:
```
  <Stack.Navigator
    screenOptions={{
      navigationBarColor: 'transparent',
      navigationBarTranslucent: true,
      navigationBarHidden: false,
    }}>
```

### CODE REVIEW

**Review by satya164 — APPROVED** [review]

**Review by satya164 — APPROVED** [review]

**Comment by jvgeee** [comment]
@alduzy @satya164 is this feature available on v6.11.x? I'm not seeing `navigationBarTranslucent` as an available in `screenOptions` (or anywhere else)

**Comment by alduzy** [comment]
@linnett @jvgeee It's available from v7 (https://github.com/react-navigation/react-navigation/blob/26463c8a6ee3814e0166b312bb8df398216604c6/packages/native-stack/CHANGELOG.md?plain=1#L147)

**Comment by linnett** [comment]
@alduzy Damn... Please can you recommend a way to fix this on 6.* , given this is a bug?  I can't upgrade to a pre-release.

**Comment by alduzy** [comment]
@linnett you can apply the changes with a patch. Please note that you must be using react-native-screens v3.32.0 or newer for it to work. @satya164 Are you planning to bring this feature to v6?

**Pull request merged**
