### PR TITLE
Update withOrientation.js

### PR DESCRIPTION
**Pull request by FernandoPailhe**
Please provide enough information so that others can review your pull request.

**Motivation**

Explain the **motivation** for making this change. What existing problem does the pull request solve?

If this pull request addresses an existing issue, link to the issue. If an issue is not present, describe the issue here.

**Test plan**

Describe the **steps to test this change** so that a reviewer can verify it. Provide screenshots or videos if the change affects UI.

The change must pass lint, typescript and tests.

### CODE REVIEW

**Comment by osdnk** [comment]
Hey, @FernandoPailhe 
Is that ready?

**Comment by FernandoPailhe** [comment]
Yes, this little fix in my project allow me to use video player in iOS. Since the last updates of expo it start to crash when goback from any screen with change orientation

**Comment by FernandoPailhe** [comment]
> Hey, @FernandoPailhe 
> Is that ready?
> 

it s the first time i edit some public library, in the package.json maybe dont need any change except for the version number

**Comment by osdnk** [comment]
i don't think this PR works (`this.dimensionsSubscription` is not defined. Please, do not edit `package.json`. Also, note that 4.x version is no longer supported.

**Comment by osdnk** [comment]
Closing due to the lack of activity

**Pull request closed without merging**
