### PR TITLE
SafeAreaView style and inset padding should collapse

### PR DESCRIPTION
**Pull request by Freddy03h**
Adding style's padding to the safe area inset isn't the way to designing with safe area on iPhone X.

For example :
```
<SafeAreaView
  forceInset={{ vertical: 'never' }}
  style={{ paddingHorizontal: 10 }}
>
```
will result, on landscape, with a total paddingHorizontal of `54` (`44` inset + `10`) but It should be `44`. Style's padding style shouldn't be added to the safe area padding.

For website, Apple say to use `safe-area-inset-*` with  css `max()` function : [https://webkit.org/blog/7929/designing-websites-for-iphone-x/](https://webkit.org/blog/7929/designing-websites-for-iphone-x/)

```
padding-left: max(10px, env(safe-area-inset-left));
padding-right: max(10px, env(safe-area-inset-right));
```

So we can achieve the same behavior with `Math.max()`

### CODE REVIEW

**Comment by vonovak** [comment]
@davepack this might of interest for you.

**Comment by Freddy03h** [comment]
Some update about this PR ?

**Comment by davepack** [comment]
Sorry for the delay on this, I haven’t been very involved lately.

**Comment by Freddy03h** [comment]
Thank you ! 😄

**Pull request merged**
