### PR TITLE
fix: the theme property of the material-bottom-tabs component does no…

### PR DESCRIPTION
**Pull request by AsteriskZuo**
…t take effect (#11444)

fix: the theme property of the material-bottom-tabs component does not take effect

**Motivation**

[fix bug](https://github.com/react-navigation/react-navigation/issues/11444)

**Test plan**

The following code checks if 'theme' is in effect.
Code prototype from [react-native-chat-library](https://github.com/AsteriskZuo/react-native-chat-library/blob/dev/example/src/screens/Home.tsx)
```typescript
import { createMaterialBottomTabNavigator } from '@react-navigation/material-bottom-tabs';
import { MD3LightTheme, MD3Theme } from 'react-native-paper';

const Home = createMaterialBottomTabNavigator<RootParamsList>();

type HomeScreenInternalProps = {
  contactFlag: React.RefObject<boolean>;
};

const HomeScreenInternal = React.memo((_: HomeScreenInternalProps) => {
  const shifting = true;
  const theme = {
    ...MD3LightTheme,
    colors: { ...MD3LightTheme.colors, secondaryContainer: 'red' }, // for test
  } as MD3Theme;
  return (
    <Home.Navigator
      initialRouteName="ConversationList"
      shifting={shifting}
      labeled={false}
      activeColor="blue"
      inactiveColor="black"
      barStyle={{ backgroundColor: 'white' }}
      theme={theme}
    >
      <Home.Screen
        name="ConversationList"
        options={() => {
          return {
            tabBarIcon: ({ color }) => {
              return (
                <View
                  style={{ backgroundColor: color, width: 30, height: 30 }}
                />
              );
            },
          };
        }}
        component={ConversationList}
      />
      <Home.Screen
        name="Contact"
        options={() => {
          return {
            tabBarIcon: ({ color }) => {
              return (
                <View
                  style={{ backgroundColor: color, width: 30, height: 30 }}
                />
              );
            },
          };
        }}
        component={ContactScreen}
      />
    </Home.Navigator>
  );
});
```

### CODE REVIEW

**Comment by borisvorobev** [comment]
Does this fix work for you? @AsteriskZuo

**Comment by AsteriskZuo** [comment]
> Does this fix work for you? @AsteriskZuo

Yes.

**Comment by AsteriskZuo** [comment]
Is there any doubt? Merge as soon as possible to solve the problem.

**Comment by AsteriskZuo** [comment]
Please tell me why can't we merge? Or you can fix it yourself.

**Comment by osdnk** [comment]
Hi,
Please open the PR to react-native-paper

**Pull request closed without merging**
