### PR TITLE
fix: add `ScrollView` type to 'getScrollResponder'

### PR DESCRIPTION
**Pull request by ken0nek**
Recreation of https://github.com/react-navigation/react-navigation/pull/10775 due to the git changes.

**Motivation**

Close https://github.com/react-navigation/react-navigation/issues/10722

`getScrollResponder` has a type error around `SectionList` due to missing type for `SectionList`

-----

FlatList - https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-native/index.d.ts#L4057

```ts
    getScrollResponder: () => JSX.Element | null | undefined;
```

SectionList - https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-native/index.d.ts#L4294

```ts
    getScrollResponder(): ScrollView | undefined;
```

**Test plan**

Use
- `@types/react`: `^18.0.15` 
- `@react-navigation/native`: `ken0nek/react-navigation.git#react-navigation-native-v6.1.1-gitpkg`

Check no errors for `useScrollToTop` with `SectionList`.

```ts
const sectionList = useRef<SectionList>(null);
useScrollToTop(sectionList);
```

### CODE REVIEW

**Comment by ken0nek** [comment]
@TomCorvus I recreated a pull request (the same diff). Could you try `"ken0nek/react-navigation.git#react-navigation-native-v6.1.1-gitpkg"`?

```sh
yarn add ken0nek/react-navigation.git#react-navigation-native-v6.1.1-gitpkg
```

**Comment by ken0nek** [comment]
@satya164 I recreated https://github.com/react-navigation/react-navigation/pull/10775 as you suggested. Please review this when you have a chance. Thank you!

ref: https://github.com/react-navigation/react-navigation/pull/10775#issuecomment-1328346381

**Comment by TomCorvus** [comment]
> @TomCorvus I recreated a pull request (the same diff). Could you try `"ken0nek/react-navigation.git#react-navigation-native-v6.1.1-gitpkg"`?
> 
> 
> 
> ```sh
> 
> yarn add ken0nek/react-navigation.git#react-navigation-native-v6.1.1-gitpkg
> 
> ```

It seems to be fixed 👍

**Comment by ken0nek** [comment]
@TomCorvus Thank you for the update! 🤝

**Review by satya164 — APPROVED** [review]
Thanks for the PR

**Pull request merged**
