### PR TITLE
fix mismatch of `pathToRegexp#compile` method

### PR DESCRIPTION
**Pull request by OguzhanE**
In old package version(1.7.0), there is no `compile` method and I am getting `undefined function` exception.
Because of v1.7.0 is depraced, its new maintain repo is https://github.com/pillarjs/path-to-regexp.

 Just upgrade package version to fix `undefined function` exception. `Compile` method exists in new version.

### CODE REVIEW

**Comment by vonovak** [comment]
@OguzhanE can you fix the flow error?

**Comment by brentvatne** [comment]
@ericvicenti - any idea what is up here?

**Comment by ericvicenti** [comment]
This looks good. I think we were just using an old version from last year.

The yarn lock file is not updated, so maybe thats why tests failed. Please rebase and run yarn, hopefully this passes and we can land it

**Comment by brentvatne** [comment]
pathToRegexp 1.7.0 does include the compile method:

```
/**
 * Expose `pathToRegexp`.
 */
module.exports = pathToRegexp
module.exports.parse = parse
module.exports.compile = compile
module.exports.tokensToFunction = tokensToFunction
module.exports.tokensToRegExp = tokensToRegExp
```

see https://unpkg.com/path-to-regexp@1.7.0/index.js

also see the typescript interface https://unpkg.com/path-to-regexp@1.7.0/index.d.ts

further, i pulled this pr locally, updated yarn.lock, ran the tests and we get the same failures. so i'm closing this pr as it does not seem to fix anything and it breaks tests. it would be good to understand if we need to upgrade path-to-regexp at some point but we should motivate that by a failing test / use case.

**Pull request closed without merging**
