### PR TITLE
feat: add hideKeyboardOnSwipe prop from react-native-screens to native-stack

### PR DESCRIPTION
**Pull request by gabrieldonadel**
**Motivation**

This PR adds the missing `hideKeyboardOnSwipe` prop from react-native-screens to react-navigation/native-stack.

This is prop is essential if we need to hide the keyboard on the swipe gesture and it is set to `false` by default since it is not the default native behavior.

In order to use this prop thought I had to upgrade `react-native-screens` to 3.15.0

**Test plan**

All tests passed.

- yarn typescript
- yarn lint
- yarn test
- yarn example start runs

### CODE REVIEW

**Comment by gabrieldonadel** [comment]
@kacperkapusciak any updates on this?

**Comment by gabrieldonadel** [comment]
@kacperkapusciak could you take another look at this please?

**Comment by kacperkapusciak** [comment]
@gabrieldonadel I hesitate so badly to add this prop as the behavior this prop introduces is janky and far from perfect

https://user-images.githubusercontent.com/39658211/194919503-01a72517-47c9-477a-ad36-c1e8d57f98ff.mp4

on the other hand keyboard animation in the JS stack `keyboardHandlingEnabled` works smoothly:

https://user-images.githubusercontent.com/39658211/194919866-a373fdd0-72c9-48b7-9f9e-f808d4f7094b.mp4

**Comment by satya164** [comment]
Hello, the PR got closed automatically due to some changes in the main branch. Would you be able to send a new PR? Thank you.

**Pull request closed without merging**
