### PR TITLE
feat(header): add accessibility label to drawer menu button

### PR DESCRIPTION
**Pull request by gianlucalippolis**
This PR adds an accessibilityLabel to the drawer menu button in the header to improve the app’s accessibility for screen reader users and fix https://github.com/react-navigation/react-navigation/issues/12173

### CODE REVIEW

**Review by satya164 — CHANGES_REQUESTED** [review]
Thanks for the PR.

Have you checked what the native hamburger menu says? I believe it says "Show navigation menu". Please check and update the text to match native behavior.

Also hardcoding the text like this means it's always going to be in English, regardless of app's language. You need to add it as a default parameter so it's possible to override the text.

**Comment by gianlucalippolis** [comment]
hi @satya164, thanks for the review and suggestions. Currently the reader says “Show navigation menu” and the text is actually fixed. I update the pull request by adding the ability to override this text via a parameter.

**Comment by satya164** [comment]
> Currently the reader says “Show navigation menu” and the text is actually fixed

The PR diff shows "Open navigation menu"

**Comment by dmathisen** [comment]
@gianlucalippolis 

> Currently the reader says “Show navigation menu”

It says "Open" in this PR's file changes. Did you forget to push an update?

> ...I update the pull request by adding the ability to override this text via a parameter.

But this is not overridable...
`accessibilityLabel="Open navigation menu"`

Don't you need something like...
`accessibilityLabel={ props.accessibilityLabel ?? "Show navigation menu" }`

**Comment by gianlucalippolis** [comment]
My mistake, the text I had set was “Show navigation menu.” I just pushed the latest updates with the changes you suggested.

**Comment by satya164** [comment]
It still says "Open navigation menu" instead of "Show navigation menu" and there are other changes besides `DrawerToggleButton`.

**Comment by gianlucalippolis** [comment]
@satya164 it's ok now?

**Comment by dmathisen** [comment]
Bump (I'm old school. Is there a better way to do that?)
@satya164

**Comment by dmathisen** [comment]
What's the blocker here? This is a REALLY bad issue.

**Comment by satya164** [comment]
Please stop pinging me multiple times. You can easily pass the prop yourself by rendering `DrawerToggleButton` if it's super critical to you. Either way, please don't ping maintainers in open source projects. I can see that there's a pull request in the repo. Pinging doesn't change anything except flood my already overwhelmed list of notifications.

I have already reviewed this PR multiple times and asked for these specific changes https://github.com/react-navigation/react-navigation/pull/12185#issuecomment-2400180893 - the PR still changes other things. I don't have the energy to keep repeating the same thing again and again.

**Comment by gianlucalippolis** [comment]
I do not understand exactly what the excess changes are, and it was not my intention to waste your time. I just tried to make a small contribution of my own. In order not to waste my time as well, I would like to understand if I can proceed with a new pull request, on a new branch by better checking my changes.

**Comment by satya164** [comment]
@gianlucalippolis it's not necessary, i just did the change here https://github.com/react-navigation/react-navigation/commit/a98eb8ce659f75ca11892aa92f96bd5f755ced6e

**Pull request closed without merging**
