### PR TITLE
fix: fix header buttons not pressable when headerTransparent=true & headerMode=float

### LINKED ISSUE #8731: cant click on header icons when headerTransparent=true and headerMode="float" in react navigation v5 android
when headerTransparent is true or headerMode is float i cant click on header icons but when i set  headerTransparent to false OR 
headerMode to screen everything working fine
`const headerdefaultStyle = {
  headerTransparent: true,
  headerTitleAlign: 'center',
  headerTitleStyle: {
    fontFamily: Fonts.type.iranSans
  },
  headerTintColor: 'white',
  headerBackTitleVisible: false
};`

`const HomeStackScreen = ({navigation}) => (
  <HomeStack.Navigator
    screenOptions={{
      headerRight: () => <DrawerIcon navigation={navigation} />,
      ...headerdefaultStyle,
      ...transitionAnimation
    }}
    headerMode="float">
    <HomeStack.Screen
      name="Home"
      component={HomeScreen}
      options={{
        headerLeft: () => <NotificationBell />,
        title: 'yas'
      }}
    />
    <HomeStack.Screen
      name="TabloGol"
      component={TabloGol}
      options={{
        title: 'tablo'
      }}
    />
  </HomeStack.Navigator>
);`

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| android       | 10
| @react-navigation/native       | ^5.7.3
| @react-navigation/stack        | ^5.9.0
| react-native-gesture-handler   | ^1.6.1
| react-native-safe-area-context | ^0.7.3
| react-native-screens           | ^2.9.0
| react-native                   | 0.62.2
| node                           | 10.16.3

### PR DESCRIPTION
**Pull request by listiani13**
Motivation
--
Previously when using `headerMode="float"` with headerTransparent set to true, we cant press header buttons in Android. This PR fixes this. (resolves #8731 )
Been doing some debugging and found out that this is caused by `HeaderContainer` being set as `absolute`. Initially it didn't have width & height in Android when it's set to default, that's why we can't access the children.
So, the solution in this PR is to define the height by using headerHeight. But, since we can't access headerHeight from header, Im using local state for keeping up with the headerHeight. Or should I move the HeaderHeight provider out of StackContainer? I'm not sure, since I think it was intended to be kept inside the StackContainer

Test Plan
--
With this config, now the header button can be clicked. Tested in both platform
```typescript
  <Stack.Navigator
    headerMode="float"
    screenOptions={{
      headerTransparent: true
    }}
  >
     <Stack.Screen  
      name="Home Screen"
      component={Home}
      />
      <Stack.Screen  
      name="Details Screen"
      component={Details}
      />
  </Stack.Navigator>
```

Android:
-
Kapture 2020-09-30 at 19 01 21

iOS:
--

### CODE REVIEW

**Comment by satya164** [comment]
Thanks for the PR. Can you provide a test plan?

**Comment by listiani13** [comment]
@satya164 just added the test plan :)

**Comment by thatguyyoulove** [comment]
Thanks for this fix. This was a blocking issue for us to release an update after upgrading navigation.

**Review by thatguyyoulove — APPROVED** [review]
Works great. Passes tests.

**Pull request merged**
