### PR TITLE
Allow Explicitly Setting Gesture Direction and Show Proper Transition Direction

### PR DESCRIPTION
**Pull request by rjacobskind**
**Motivation:** 
I have a project with a custom transitionConfig that has some app screens entering from the bottom of the device screen, and others entering from the right of the device screen. I wanted to allow users to use swipe gestures with these screens in a logical direction based on the way the screens entered.

### CODE REVIEW

**Comment by vonovak** [comment]
Hi! Thanks for the PR. Looking at the diff, it seems like most places that had something like `this.props.navigationConfig.mode === 'modal'` or `const isVertical = mode === 'modal'` now have 

```js
this.props.navigationConfig.mode === 'modal' ||
this.gestureDirection === 'down' ||
this.gestureDirection === 'up'
```
or

```js
const isVertical =
mode === 'modal' ||
options.gestureDirection === 'up' ||
options.gestureDirection === 'down';
```

Can you clarify why `mode === 'modal'` was not good enough for you use case?

**Comment by rjacobskind** [comment]
@vonovak In my app, I have some screens that enter from the right, and other screens that enter from the bottom, and I wanted to be able to have swipe gestures on all of them. As far as I could tell, I couldn't achieve that by setting the mode to 'modal'. Feel free to correct me if there is a simpler solution!

**Comment by vonovak** [comment]
so if I understand it correctly, `modal` is something that works on the Navigator level, while you needed to have different per-screen animations within one Navigator?

**Comment by Tomatoo** [comment]
this merge request can support different animations for stack children?

**Comment by rjacobskind** [comment]
@Tomatoo This PR supports vertical and horizontal slide gesture animations for stack children. Currently in this PR, calling 'goBack()' while using the default transition config will use the default animation to go back, regardless of gesture direction.

**Comment by brentvatne** [comment]
cc @ericvicenti - curious what you think about this

**Comment by n1ru4l** [comment]
@brentvatne @ericvicenti any updates on when we can expect this getting merged?

**Comment by rjacobskind** [comment]
I opened a new PR for this in the react-navigation-stack repo, as I noticed the stack navigation files have been separated from the project.

https://github.com/react-navigation/react-navigation-stack/pull/10/files

**Pull request closed without merging**
