### PR TITLE
Add enableKeyboardAvoiding to navigationConfig

### PR DESCRIPTION
**Pull request by yangyuan**
Add enableKeyboardAvoiding to navigationConfig, if enabled, createNavigator will wrap the NavigatorView with a KeyboardAvoidingView.

### CODE REVIEW

**Comment by yangyuan** [comment]
KeyboardAvoidingView needs keyboardVerticalOffset if the view does not start from the top of the screen.

For createStackNavigator or createMaterialTopTabNavigator there will headers and tabs.
I've seen most of the projects use magic numbers (like 64 for ios, 54+StatusBar.currentHeight for Android, and special case for iPhone X, iPad, horizontal iPhone X...) to set the keyboardVerticalOffset. Which is a bad idea.

We can extend the navigators to add a KeyboardAvoidingView. However, it will be duplicated work, especially in some UI structure like this:
```
<BottomTabNavigator>
  <KeyboardAvoidingView>
    <StackNavigator />
  </KeyboardAvoidingView>
</BottomTabNavigator>
```

I think the better idea is to let react-navigation to take care of this. So I suggest to add a new paramater in navigationConfig.
For example:
```
createStackNavigator({...}, { enableKeyboardAvoiding: true });
```

**Comment by brentvatne** [comment]
hey! this is interesting. could you submit a RFC that details this more? thanks! https://github.com/react-navigation/rfcs

**Comment by brentvatne** [comment]
closing until rfc

**Comment by scottyantipa** [comment]
It would be really nice to get this in. I currently have to remove react-navigation headers, and make my own, to get KeyboardAvoidingView working properly. @yangyuan is this being worked on?

**Comment by brentvatne** [comment]
@scottyantipa - want to open a RFC? http://github.com/react-navigation/rfcs

**Comment by yangyuan** [comment]
@brentvatne I will open a RFC today.

**Comment by yangyuan** [comment]
Hi @brentvatne I've created the RFC. https://github.com/react-navigation/rfcs/pull/58

**Pull request closed without merging**
