### PR TITLE
fix: refactored tabBarIcon

### PR DESCRIPTION
**Pull request by myckhel**
Fix for duplicate tabBarIcon issue https://github.com/react-navigation/react-navigation/issues/9272

### CODE REVIEW

**Comment by myckhel** [comment]
installation from forked repo:
`yarn add https://github.com/myckhel/react-navigation.git#react-navigation-bottom-tabs-v5.11.7-gitpkg`

**Comment by satya164** [comment]
There are 2 icons overlaid to prevent any rendered images from flickering when changing. You shouldn't be using it to perform any side effects. Do those side effects inside your screen.

**Comment by myckhel** [comment]
💔😔😒

I guess there is no other way to achieve the real time badge counter update i was trying to do.

Since the screen is not automatically focused so i won't be able to set the screen options for bagdeCount. 

Does this changes produces the image flickering issue?

Is there any other way we can try not to create 2 tabBarIcons?

**Comment by myckhel** [comment]
Please can you respond to my questions?

**Pull request closed without merging**
