### PR TITLE
fix: status bar height for iOS devices with dynamic island

### PR DESCRIPTION
**Pull request by gianlucalippolis**
This PR addresses the issue https://github.com/react-navigation/react-navigation/issues/11655

### CODE REVIEW

**Comment by outaTiME** [comment]
Hi @gianlucalippolis, 
be careful, probably the value that should be used is 5.33 instead of 6 for a perfect fit.

https://github.com/react-navigation/react-navigation/pull/11338#pullrequestreview-1725831043

**Comment by gianlucalippolis** [comment]
hi @outaTiME, you are right, by reducing that value from 6 to 5.33 the bug is fixed anyway. I tried reducing it further to 5.2, is there any particular reason why you suggest the value 5.33?

**Comment by outaTiME** [comment]
Here is the original hot fix and report:

https://github.com/react-navigation/react-navigation/issues/10989#issuecomment-1396251186

Now I don't remember well, but I understand that the `UINavigationBar` returns `53.67` as a fixed value for devices with dynamic island and the `useHeaderHeight` returns `59`, from the difference of both values comes the number `5.33`

**Comment by satya164** [comment]
Where does the `0.17` come from? As @outaTiME mentioned the `0.33` makes sense as it's like the height of the border that needs to be removed, which is `1 / PixelRatio.get()`.

**Comment by gianlucalippolis** [comment]
I set that value because it covered the screen perfectly. I will still make the change by setting 0.33 as you suggest.  I will also try moving that logic to getDefaultHeaderHeight.

Thanks

**Comment by gianlucalippolis** [comment]
@satya164 @outaTiME i updated the PR.

**Review by satya164 — APPROVED** [review]
Thanks!

**Pull request merged**
