### PR TITLE
added hiddenTabs property for TabBarBottom component

### PR DESCRIPTION
**Pull request by Arekkusuva**
Now you can pass `hiddenTabs` property (array with tabs indexes) to `TabBarBottom` component. That allows you to hide certain tabs dynamically.

### CODE REVIEW

**Comment by satya164** [comment]
Why do you need to render a tab if there's no way to access it?

**Comment by Arekkusuva** [comment]
@satya164 What do you mean?

**Comment by satya164** [comment]
Please explain the use case behind the PR. This PR hides the entry in the tab bar while the page is still rendered. Why do you need this feature?

**Comment by Arekkusuva** [comment]
@satya164 I needed ability to hide certain tabs from TabBar dynamically. And i believe that's the fastest way to do this. Also you can set `lazy` property to true if you don't want to render hidden tabs.

**Comment by Arekkusuva** [comment]
@satya164 And I believe we can control the rendering of certain pages with standard methods of this library and React. `lazy` property only one of several methods to do this.

**Comment by satya164** [comment]
> I needed ability to hide certain tabs from TabBar dynamically

What's the use case that requires hiding tab items from tab bar, but not from the rendered pages?

> Also you can set lazy property to true if you don't want to render hidden tabs.

`lazy` option was removed. Also, that's not how it used to work. It was used to load tabs laziliy until you access them for the first time, and they still stay rendered after you navigate away.

Anyway, can you describe the use case? I know you want to hide an item from tab bar, but "why"? It's not possible to decide if this is a reasonable change if you don't explain the use case.

**Comment by nikasvan** [comment]
@satya164 Use case for this would be:

Using StackNavigator, TabNavigator and DrawerNavigator in the app and trying to show TabBar inside DrawerNavigator screens. Here is my [Stackoverflow question](https://stackoverflow.com/questions/47889379/making-tabnavigators-tabbar-always-visible-on-every-route-of-the-app) which I have asked 4-5 times before this and got no answer from anyone. 

@Arekkusuva Thanks for this, I did something similar to this and it should be merged. Just one thing though did you make it to work for android(in TabBarTop.js, I think)?

**Comment by Arekkusuva** [comment]
@satya164 I use this in react native project to allow users customize UI.

**Comment by Arekkusuva** [comment]
@nikasvan If you know how to implement this better, then do it please. Since I'm not that good at this library.

**Comment by nikasvan** [comment]
@Arekkusuva I was asking this because I have not been able to do it for Android yet:D. 

If you would like your PR to be merged most important rule is to make sure that it works both for iOs and Android as well!

**Comment by Arekkusuva** [comment]
@nikasvan Well, i’ll check it tomorrow. Also i will try to remove hidden tabs from rendered pages.

**Comment by satya164** [comment]
> Using StackNavigator, TabNavigator and DrawerNavigator in the app and trying to show TabBar inside DrawerNavigator screens.

You need to have a custom TabBar if you want to collapse multiple items to one item. Just hiding items won't solve your use case. You still need a custom tab bar to be able to show a "more" button. And if you are making your custom tab bar, it's straightforward to hide some items.

> I use this in react native project to allow users customize UI.

That still doesn't explain the use case. Why do you want to hide tab items when the pages are still rendered?

**Comment by Arekkusuva** [comment]
@satya164 I’ll try to do this later. I mean pages.

**Comment by nikasvan** [comment]
So Found the solution for Android. The thing is that for Android react-navigation is using [react-native-tab-view](https://github.com/react-native-community/react-native-tab-view). So to make it work what needs to change is in _react-native-tab-view/src/TabBar.js_ on line 449 just after components `return` statement add `this.props.hideIndex.indexOf(i) > -1 ? null : <TouchableItem.......` http://prntscr.com/i45qr8

**Comment by brentvatne** [comment]
closing this, please make the required change in react-native-tab-view if they will accept it :) then open a pr here and follow the pull request template

```
Please provide enough information so that others can review your pull request:

Explain the **motivation** for making this change. What existing problem does the pull request solve?

Prefer **small pull requests**. These are much easier to review and more likely to get merged. Make sure the PR does only one thing, otherwise split it.

**Test plan (required)**

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

Make sure you test on both platforms if your change affects both platforms.

The code must pass tests.

**Code formatting**

Look around. Match the style of the rest of the codebase.
```

**Comment by brentvatne** [comment]
oh and of course thank you so much for taking the time to open this in the first place :) sorry we didn't come to a solution that we can land here, looking forward to the follow up if you're still motivated

**Pull request closed without merging**
