### PR TITLE
feat: drawerType sidebar for drawer

### PR DESCRIPTION
**Pull request by hosseinmd**
For drawer opens always, add a sidebar to `drawerType` to do this.

Based on discussed [here](https://github.com/react-navigation/navigation-ex/pull/301)

### CODE REVIEW

**Comment by jasperjorna** [comment]
Very nice and needed feature!

**Comment by pincheira** [comment]
I really love this. 

It avoids so many hacks to have the sidebar rendering 2 drawers just to do this.

@hosseinmd thanks man!
# 👏🏼

**Comment by pincheira** [comment]
Uh oh. The latest commits seems to have broken it. Can't launch it anymore using `yarn example start`. 😞

**Comment by hosseinmd** [comment]
> Uh oh. The latest commits seems to have broken it. Can't launch it anymore using `yarn example start`. 😞

The example is working but ci doesn't work.

**Comment by pincheira** [comment]
I ran `yarn; yarn example start` but it throws:

```
$ expo start
Starting project at /Users/jp/Work/spare/sidebar/react-navigation/example
Expo DevTools is running at http://localhost:19003
Opening DevTools in the browser... (press shift-d to disable)
Some of your project's dependencies are not compatible with currently installed expo package version:
 - react-native-reanimated - expected version range: ~1.4.0 - actual version installed: ^1.7.0
 - react-native-screens - expected version range: 2.0.0-alpha.12 - actual version installed: ^2.0.0-beta.2
 - react-native-safe-area-context - expected version range: 0.6.0 - actual version installed: ^0.7.2
 - @react-native-community/masked-view - expected version range: 0.1.5 - actual version installed: 0.1.6
Your project may not work correctly until you install the correct versions of the packages.
To install the correct versions of these packages, please run: expo install [package-name ...]
error ENOENT: no such file or directory, open '/Users/jp/Work/spare/sidebar/react-navigation/packages/native-stack/package.json'.

Error: ENOENT: no such file or directory, open '/Users/jp/Work/spare/sidebar/react-navigation/packages/native-stack/package.json'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at modules.concat.fs.readdirSync.filter.map.p (/Users/jp/Work/spare/sidebar/react-navigation/example/metro.config.js:21:14)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/Users/jp/Work/spare/sidebar/react-navigation/example/metro.config.js:19:8)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Metro Bundler process exited with code 1
Set EXPO_DEBUG=true in your env to view the stack trace.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
➜  react-navigation git:(drawerSidebar) ✗
```

Any ideas? Thank you 🙏

**Comment by pincheira** [comment]
Looks like @satya164 has this planned https://react-navigation.canny.io/feature-requests/p/sticky-side-menu-for-tablets

**Comment by hosseinmd** [comment]
> I ran `yarn; yarn example start` but it throws:
> 
> ```
> $ expo start
> Starting project at /Users/jp/Work/spare/sidebar/react-navigation/example
> Expo DevTools is running at http://localhost:19003
> Opening DevTools in the browser... (press shift-d to disable)
> Some of your project's dependencies are not compatible with currently installed expo package version:
>  - react-native-reanimated - expected version range: ~1.4.0 - actual version installed: ^1.7.0
>  - react-native-screens - expected version range: 2.0.0-alpha.12 - actual version installed: ^2.0.0-beta.2
>  - react-native-safe-area-context - expected version range: 0.6.0 - actual version installed: ^0.7.2
>  - @react-native-community/masked-view - expected version range: 0.1.5 - actual version installed: 0.1.6
> Your project may not work correctly until you install the correct versions of the packages.
> To install the correct versions of these packages, please run: expo install [package-name ...]
> error ENOENT: no such file or directory, open '/Users/jp/Work/spare/sidebar/react-navigation/packages/native-stack/package.json'.
> 
> Error: ENOENT: no such file or directory, open '/Users/jp/Work/spare/sidebar/react-navigation/packages/native-stack/package.json'
>     at Object.openSync (fs.js:443:3)
>     at Object.readFileSync (fs.js:343:35)
>     at modules.concat.fs.readdirSync.filter.map.p (/Users/jp/Work/spare/sidebar/react-navigation/example/metro.config.js:21:14)
>     at Array.map (<anonymous>)
>     at Object.<anonymous> (/Users/jp/Work/spare/sidebar/react-navigation/example/metro.config.js:19:8)
>     at Module._compile (internal/modules/cjs/loader.js:778:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
> Metro Bundler process exited with code 1
> Set EXPO_DEBUG=true in your env to view the stack trace.
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ➜  react-navigation git:(drawerSidebar) ✗
> ```
> 
> Any ideas? Thank you 🙏

remove node_modules and packages/native-stack if exist.

**Comment by kopax** [comment]
Thanks for this awesome feature.

I was asking for #7488, do you know if the menu can stay open and the content container positioned right to the menu (and not under)?

Also, I would like to dock the sidebar when the viewport with is greater than 800px on the web, should this be possible?

Perhaps an example of implementation could be helpful.

Thanks again!

**Comment by pincheira** [comment]
Are there any plans on merging this? cc/  @satya164

**Comment by hosseinmd** [comment]
Example code is:
```js
 

> Thanks for this awesome feature.
> 
> I was asking this in #7488, do you know if the menu can stay open and the content container positioned right to the menu (and not under) (also known as `docked` sidebar)?
> 
> Also, I would like to dock the sidebar when the viewport with is greater than 800px on the web, should this be possible?
> 
> Perhaps an example of implementation could be helpful.
> 
> Thanks again!

In this PR, an example of a sidebar drawer is provided. 
improve the example, for what you want to know.
https://github.com/poolkhord/react-navigation/blob/drawerSidebar/example/src/index.tsx

This part of the example code maybe helps you.
```js
<Drawer.Navigator
      drawerType={width > 800 ? 'sidebar' : 'front'}
      ...
      >
```

Thank you.

**Comment by hosseinmd** [comment]
I closed this PR because @satya164 added permanent to drawerType that is like sidebar

**Pull request closed without merging**
