### PR TITLE
#1053 throw warning when navigate to an invalid route

### LINKED ISSUE #1053: Throw warning or error when navigate to an invalid route
I made a typo on one of my `this.props.navigation.navigate('routeName`)` and it was hard to figure it out 

can we throw a warning or an error when this happens?

### PR DESCRIPTION
**Pull request by azisuazusa**
This PR should be resolve #1053

### CODE REVIEW

**Comment by vonovak** [comment]
I didn't run the code but just looking at it, I don't think it can work right.

**Comment by matthamil** [comment]
Technically this isn't throwing a warning--it's only logging. I'm open to what the community would prefer here--an actual error being thrown or a console.info so the typical React Native Yellow Box appears during development. I think it might be best to throw an error.

**Comment by kelset** [comment]
@azisuazusa as @matthamil said, I think it would be better to throw an actual error. Can you update your PR? I'd love to merge it once the change has been done.

**Comment by brentvatne** [comment]
This PR is a decent approximation, but it isn't exactly correct &mdash; imagine a situation where you have a `TabNavigator` without any stack, and in one of those screens in the `TabNavigator` you navigate to a route that doesn't exist. Same for drawer and other custom navigators.

Additionally, these warnings should only occur in development mode (`__DEV__` must be `true`).

I'm not sure at the moment how I'd implement this in a way that would work with any router. Open to ideas though! Closing this PR for now as it doesn't solve the problem.

**Pull request closed without merging**
