### PR TITLE
feat: allow hiding of routes in DrawerItemList

### PR DESCRIPTION
**Pull request by ROODAY**
I made this based on my own issue #7962 ([plus it seems like a lot of people have wanted this for a while](https://www.google.com/search?q=react+navigation+hide+drawer+item)).

What this proposes is that now users can define a list of routes they want to be visible when defining a custom `drawerContent` component:
```
function CustomDrawerContent(props) {
  return (
    <DrawerContentScrollView {...props}>
      <DrawerItemList {...props} visibleRoutes={["Home", "Login", "Settings"]} />
    </DrawerContentScrollView>
  );
}
```

This would then filter out any routes not in the `visibleRoutes` prop. If `visibleRoutes` is not set, it will fallback to using `state.routeNames` and display all the routes.

### CODE REVIEW

**Comment by ROODAY** [comment]
I've never used TypeScript before, so I think one thing I missed was defining a type for this new prop I added. Could someone point me to some relevant docs/tutorials so I can add checking that `visibleRoutes` is either an array of `Route<String>` or `undefined`?

**Comment by ROODAY** [comment]
Is that Circle CI lint failure going to be enforced? If I understand it correctly it wants me to put the filter call on a newline, but then shouldn't the map call also be put on a newline? I was just trying to follow the style inside the file, could a maintainer advise?

**Comment by ROODAY** [comment]
Hi @satya164, could I get a review when you get a chance?

**Comment by xstable** [comment]
Good approach, but wouldn't it be better to have an parameter working in the opposite way? Means to hiddenRoutes={["Secret", "Login", "Imprint"]}. 
This would minimize the size of data to add to this property, because generally there will be most of the time more Items to show as to hide.

**Comment by ROODAY** [comment]
@xstable Sounds good, just made an update!

**Comment by satya164** [comment]
Thanks for the PR.

Why not put the screen in a parent/child stack navigator if you don't want it to be displayed in the drawer sidebar? It could be confusing to the user have a screen rendered, but not have anything selected in the drawer.

**Comment by ROODAY** [comment]
@satya164 That's fair, at the time I was developing a class project and we just needed to get it out by the deadline and hiding the drawer item was the fastest solution (the specific screen was an article screen after a user clicked an article card, we didn't want users to navigate to the article screen through the drawer, only when they clicked the corresponding article card). If I were to go back and refactor it, I guess the way you described would be the most idiomatic (placing the article screen inside a stack navigator for the home screen).

**Comment by samipshah100** [comment]
This fits my use case where by I don't want to nest navigators because: 
1. I am navigating conditionaly, between routes hence I don't always know if the navigator is nested. 
2. Using Deep links so need the navigation routes state to be as flat as possible

**Comment by satya164** [comment]
I'm closing the issue. We recommend nesting a stack inside if you don't want to show a screen in drawer/tabs.

@samijaber not sure why deep links would require flat state.

**Comment by cabhara** [comment]
How can drawerItems be hidden by nesting a stack?

**Pull request closed without merging**
