### PR TITLE
 fix: possible to open 2 screens while minimizing the app (#6963)

### LINKED ISSUE #6963: Two or more screens could be opened at the same time using back swipe
**Current Behavior**

Here is an reproducible example https://snack.expo.io/ryjmtfwM8

- Include a screenshot or video if it makes sense.
RPReplay_Final1580906837

**Expected Behavior**

Screen is expected not to stuck after opening. (react-navigation-stack: "^1.10.3")
RPReplay_Final1580908007

**How to reproduce**

1) Install the app
2) Tap 'Go to Details'
3) Start the swipe right from the left edge of the screen and spot at the center
4) Minimize the app
5) Open app

**Your Environment**

| software                              | version |
| --------------------------| ------- |
| iOS or Android                   | any
| react-navigation                | ^4.0.10"
| react-navigation-stack      | "^2.1.1"
| react-native-gesture-handler   | "^1.5.1"
| react-native-safe-area-context | "^0.6.0"
| react-native-screens           | "^2.0.0-beta.1"
| react-native                   | "0.61.5"
| expo                           | 36.0.0

### PR DESCRIPTION
**Pull request by MaxBolotnyi**
Resolves #6963

### CODE REVIEW

**Comment by satya164** [comment]
Thanks for the PR. I think this PR already addresses this https://github.com/react-navigation/react-navigation/pull/7898

**Comment by MaxBolotnyi** [comment]
@satya164 looks like I missed this one, thank you

Can you advise when to expect this one to be merged?

**Comment by satya164** [comment]
I have requested changes, so I'll merge it after they are addressed.

**Comment by MaxBolotnyi** [comment]
@satya164  got it, thank you, then I am closing this one

**Comment by MaxBolotnyi** [comment]
@satya164 Can you please release this same fixed for the 4.x branch (react-navigation-stack) ?
Screenshot 2020-03-31 at 12 52 30

**Pull request closed without merging**
