### PR TITLE
Playground facelift

### PR DESCRIPTION
**Pull request by vonovak**
As discussed on slack, I added some margins around the buttons, so playground now feels a little better, especially on android. Let me know how it looks :)

### CODE REVIEW

**Comment by ericvicenti** [comment]
Thanks for working on this!

This expo preview is the coolest thing @brentvatne. Visual changes like this are so easy to test now

The black back button in the stack example seems strange on iOS

**Comment by vonovak** [comment]
@ericvicenti good point. The color will now be blue (the same color as the back label) on ios and black on android.

**Comment by brentvatne** [comment]
this is considerably improved on android, thanks! a couple things:

- I kind of liked the spacing between buttons on iOS how it was before, perhaps we could make the spacing all conditional on platform?
- It would be nice to fix the padding on tab bar top screens, as it doesn't currently factor in the translucent status bar on Android. Not sure whatt the best way to go about this is

**Comment by vonovak** [comment]
* regarding the ios margins - that will be easy
* regarding tab bar top screen - I think the proper fix would be to include a stack header, which would make the screen look better not only on android but on ios as well. What do you think?

**Comment by brentvatne** [comment]
> regarding tab bar top screen - I think the proper fix would be to include a stack header, which would make the screen look better not only on android but on ios as well. What do you think?

sounds good. I'd like to fix this so it just works out of the box but we have some more work to do on https://github.com/react-navigation/rfcs/issues/13 first

**Comment by vonovak** [comment]
> regarding tab bar top screen - I think the proper fix would be to include a stack header, which would make the screen look better not only on android but on ios as well.

I just checked and there actually already is a screen that does this ("Stacks in Tabs" is the label). So I think I will just keep it the way it is and wait until it looks correct out of the box? (or force some paddings on android?)


On android, in that "Stacks in Tabs" screen I also noticed a weird jump which is not visible before adding the margins to the buttons. It is caused by the SafeAreaView [here](https://github.com/react-navigation/react-navigation/blob/cd5bd8882ef3457a004bc04f00d436f2cd625082/examples/NavigationPlayground/js/StacksInTabs.js#L14). I did not notice the jump on other screens.

**Comment by brentvatne** [comment]
yeah let's leave it as-is then.

> On android, in that "Stacks in Tabs" screen I also noticed a weird jump which is not visible before adding the margins to the buttons. It is caused by the SafeAreaView here. I did not notice the jump on other screens.

ugh, let's handle that in a follow up PR. going to land this one now!

**Pull request merged**
