### PR TITLE
getComponentForState made more generic

### PR DESCRIPTION
**Pull request by Rabursky**
It's just one line...
routeName (and what component is being rendered) should depend directly and only on the navigation state.

### CODE REVIEW

**Comment by matthamil** [comment]
Can you explain the motivation behind this change?

**Comment by Rabursky** [comment]
@matthamil 
`order` const is being calculated only once when the router is created.
Router should render components based on its current state and not on preconfigured one from the startup.
In my project I am using TabBar as child navigator of another navigator. Parent navigator dynamically change order and availability of tabs. It doesn't work because of this one line, I had to monkey-patch the router.

Hope it explains my motivation a bit better...

**Comment by Rabursky** [comment]
@matthamil Did previous explanation help?

**Comment by satya164** [comment]
It makes sense to me that we should use the passed state to determine the component. However other methods are using `order` too. So we would need to change it.

**Pull request merged**
