### PR TITLE
Try to not initiate transition when only route parameters are changed.

### PR DESCRIPTION
**Pull request by moriyoshi**
I'm using `onTransitionStart` hook like the following to dismiss the software keyboard when the transition is triggered.  When it's used in combination with `navigation.setParams()`, the hook is triggered as opposed to my expectation; the action also initiates the no-op transition.

The changes in this PR prevents unnecessary transitions and triggering hooks around them.

```javascript
import React from 'react';
import { StackNavigator } from 'react-navigation';
import { TextInput, Text, Button, View, Keyboard } from 'react-native';


const Top = ({ navigation }) => (
  <View style={{ flex: 1, alignItems: 'center', alignContent: 'center', justifyContent: 'center' }}>
    <Text>Top</Text>
    <Button onPress={() => navigation.navigate("Form")} title="Go to Form" />
  </View>
);


class Form extends React.Component {
  static navigationOptions = ({ navigation }) => ({
    headerTitle: navigation.state.params && navigation.state.params.title,
  });
  render() {
    return (
      <View style={{ flex: 1, alignItems: 'center', alignContent: 'center', justifyContent: 'center' }}>
        <Text>Form</Text>
        <TextInput style={{ width: 300, textAlign: 'center' }} placeholder="Input here" onChange={(ev) => this.props.navigation.setParams({ title: ev.nativeEvent.text })} />
      </View>
    );
  }
}

export default StackNavigator({
  Top: { screen: Top },
  Form: { screen: Form },
}, {
  onTransitionStart: () => Keyboard.dismiss(),
});
```

| Without the hook | What I expect with the hook | What I got instead |
| --- | --- | --- |
|  |  |  |

### CODE REVIEW

**Comment by moriyoshi** [comment]
I really hope to see this get some attention as I'd rather think of this being a bug.

**Comment by vonovak** [comment]
hi @moriyoshi! So, do I understand it correctly that you're saying that `navigation.setParams()` calls `onTransitionStart` even though no transition is actually going to happen?


I'm not familiar with the `Transitioner`'s inner working, can you explain me in words what the code does? Thanks!

**Comment by moriyoshi** [comment]
> hi @moriyoshi! So, do I understand it correctly that you're saying that navigation.setParams() calls onTransitionStart even though no transition is actually going to happen?

Exactly.

> I'm not familiar with the Transitioner's inner workings, can you explain me in words what the code does? Thanks!

Previously, a transition occurs every time any one of the followings changes between the two scenes:

- key
- index
- isStale
- isActive

where `index` is to be incremented even if just the parameters are changed.  This PR modifies the behavior so that transition occurs only when the route actually changes.

**Comment by ericvicenti** [comment]
I think this will break child navigators, because the scenes reducer of the parent stack transitioner will prevent new routes (navigation states) to be provided to children navigation views.

Instead, maybe we should make it so that `Transitioner.props.onTransitionStart/End` only happens when the key actually changes. That seems to be the actual issue you're experiencing, right?

**Comment by vonovak** [comment]
fyi: if you copy `Transitioner-test.js` over to current master, the test passes, so it may be the issue got fixed in the mean time.

**Comment by brentvatne** [comment]
@vonovak - can you open a PR that adds these tests to master? then we can close this issue

**Pull request closed without merging**
