### PR TITLE
Adding activeLabelStyle prop

### PR DESCRIPTION
**Pull request by julesmoretti**
This is to create the ability to override default appearance like regular font vs bold when using the TabBarTop component. 

Issue #2082

thank you.

Please provide enough information so that others can review your pull request:

Explain the **motivation** for making this change. What existing problem does the pull request solve?

I was trying to make the active label bold compared to others while using the TabBarTop, I could have created some custom tabBarIcon but that would have been the wrong place for it.

Prefer **small pull requests**. These are much easier to review and more likely to get merged. Make sure the PR does only one thing, otherwise split it.

**Test plan (required)**

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

Could not find method to do this. edited it on my end and it works.

Make sure you test on both platforms if your change affects both platforms.

The code must pass tests.

**Code formatting**

Look around. Match the style of the rest of the codebase.

### CODE REVIEW

**Comment by julesmoretti** [comment]
@satya164 - Thank you for your response. To me, the confusion is in the component section naming. 

This is the way I visually break down the TabNavigator. So can you help shine some light on what 1 to 5 are called in the styling?

screen shot 2018-03-02 at 10 53 51 am

**Comment by satya164** [comment]
> So can you help shine some light on what 1 to 5 are called in the styling

The problem is not naming. The problem is that there are multiple states between the active and inactive state while it's animating. Having styles for active and inactive state leaves out all the intermediate states.

**Comment by julesmoretti** [comment]
Ok so what is your recommendation for having the font become bold when tab is active?

And what are the various states?

**Comment by julesmoretti** [comment]
@satya164 ?

**Comment by ericvicenti** [comment]
This project is moving over to https://github.com/react-navigation/react-navigation-tabs

Feel free to experiment with this feature in that repo.. I think it should be possible to render both labels and fade the opacity between them as the route becomes focused.

**Pull request closed without merging**
