### PR TITLE
fix: prevent back handler usage on web

### PR DESCRIPTION
**Pull request by EvanBacon**
**Motivation**

- fix https://github.com/react-navigation/react-navigation/issues/11316

**Test plan**

- ¯\_(ツ)_/¯

### CODE REVIEW

**Comment by mlennie** [comment]
how can we use this? Will this be merged soon?

**Comment by nandorojo** [comment]
Just to add relevance here, the same PR is needed on expo's action sheet: https://github.com/expo/react-native-action-sheet/blob/a918aec7706629058c270fcd083fed7ca547826a/src/ActionSheet/CustomActionSheet.tsx#L231

**Review by kacperkapusciak — APPROVED** [review]

**Comment by kamathpavank** [comment]
Could you please provide an update on when these changes are expected to be published on the npm package registry

**Comment by Jackman3005** [comment]
Hi @EvanBacon assuming the work you did on this is all good to go, is there a reason we're waiting on an updated release with the changes?

Thanks in advance!

**Pull request merged**
