### PR TITLE
refactor: replace unstable_screenStyle with backgroundColor from contentStyle

### PR DESCRIPTION
**Pull request by maciekstosio**
Corresponding PR in react-native-screens: https://github.com/software-mansion/react-native-screens/pull/2419. 

## Change

Instead of adding `unstable_screenStyle` that directly adds background on `Screen` component, we can pick the `backgroundColor` from `contentStyle` and apply it on `Screen` component, without exposing unstable prop.

### CODE REVIEW

**Review by kkafar — COMMENTED** [review]
Okay, this looks solid. 

One last thing to do would be to update description of `contentStyle` in types so that it is known that you can set it to workaround the "truncated sheet content" issue.

**Comment by kkafar** [comment]
I think you're right @satya164, but we'll keep the order here. Merge this & later migrate with your after your PR lands (because we want to include this in todays beta).

**Comment by kkafar** [comment]
Hey, https://github.com/software-mansion/react-native-screens/pull/2433 has been merged - we should be able to proceed now

**Comment by maciekstosio** [comment]
Closing in favor of: https://github.com/react-navigation/react-navigation/pull/12218/files

**Pull request closed without merging**
