### PR TITLE
feat: add prop for new container

### PR DESCRIPTION
**Pull request by WoLewicki**
Added new prop `tabsOrDrawer` for `ScreenContainer` which makes `react-native-screens` on `iOS` use new component if it is available. See https://github.com/software-mansion/react-native-screens/pull/1029 for context.

### CODE REVIEW

**Comment by swrobel** [comment]
Any hope of getting this reviewed/merged soon?

**Review by swrobel — APPROVED** [review]

**Comment by a-eid** [comment]
wondering if this is getting merged soon ?

**Comment by WoLewicki** [comment]
Can you use [patch-package](https://www.npmjs.com/package/patch-package) and check if this change does not introduce any new problems? It would be for sure a valuable insight for if it works ok in all cases.

**Comment by a-eid** [comment]
> Can you use [patch-package](https://www.npmjs.com/package/patch-package) and check if this change does not introduce any new problems? It would be for sure a valuable insight for if it works ok in all cases.

I have on a different project and it's working perfectly.

**Review by satya164 — APPROVED** [review]
Thank you

**Pull request merged**
