### PR TITLE
Add more missing Flow types

### PR DESCRIPTION
**Pull request by levibuzolic**
More exported flow types to address #6153

### CODE REVIEW

**Comment by satya164** [comment]
Is this still WIP?

**Comment by levibuzolic** [comment]
@satya164 they can probably be merged as-is for now, will get up to date with the changes in 4.x and update #6153 to ensure I've got everything covered.

**Comment by satya164** [comment]
Thank you! Can you rebase the PR against 3.0?

Regarding 4.0, we're moving them to flow-typed: https://github.com/react-navigation/react-navigation/pull/6327

**Comment by Ashoat** [comment]
Sorry I completely missed this! I just put up a "revamp" of the libdefs for 4.0 over on `flow-typed`: flow-typed/flow-typed/pull/3569

A lot of the stuff you've typed here is either missing or poorly typed in that PR, so would be great to try and merge those in. That said we'd probably want to get it in over on the `flow-typed` repo. My apologies for the churn.

**Comment by levibuzolic** [comment]
No problem, I'm happy to redirect my efforts to `flow-typed` :+1:

**Pull request closed without merging**
