### PR TITLE
feat: add detachInactiveScreens prop for bottom tabs and drawer

### PR DESCRIPTION
**Pull request by WoLewicki**
Added optional screens enabling for v4 bottom-tabs and drawer navigators.

### CODE REVIEW

**Review by matthargett — COMMENTED** [review]
Can you add/update tests that pin the behavior of the prop getting set/retained correctly?

**Review by satya164 — CHANGES_REQUESTED** [review]
Can you also update the prop names to match the changes we did in v5?

**Review by satya164 — APPROVED** [review]

**Review by satya164 — CHANGES_REQUESTED** [review]
Can you make sure the CI passes?

**Pull request merged**
