### PR TITLE
chore: allow editing styles for DrawerItem text label View wrapper

### PR DESCRIPTION
**Pull request by allandiego**
Resolve issue: https://github.com/react-navigation/react-navigation/issues/8949

### CODE REVIEW

**Comment by allandiego** [comment]
Any update for this PR? I think its a simple but usefull improvement.

**Comment by Elter71** [comment]
@allandiego please resolved conflicts, then I can check your PR

**Comment by allandiego** [comment]
hey @Elter71, check if it's okay, I had to rebase because initial pull request was made in version 5 of react navigation

**Review by Elter71 — APPROVED** [review]
Looks good to me, GJ @allandiego 👏

@satya164 Could you merge this PR?

**Comment by satya164** [comment]
Hello, the PR got closed automatically due to some changes in the main branch. Would you be able to send a new PR with more details on the use cases for the change (e.g. some screenshots of expected UI that's not possible with the current API)? Thank you.

**Pull request closed without merging**
