### PR TITLE
#9558 Fix drawer close on typing outside and swipe action on iOS.

### PR DESCRIPTION
**Pull request by Romick2005**
This can be used to fix usage react-navigation v5 with react-native-reanimated v2, because Animated.event does not work for iOS and does not give any warnings or errors. In reanimated v2 we need to use hook useAnimatedGestureHandler that is not available as v5 uses component based drawer.
This fix also applicable for navigation v6, but for legacy drawer that do not use hooks.

### CODE REVIEW

**Comment by satya164** [comment]
Thanks for the PR. This sounds like a bug in Reanimated 2? It is supposed to be backward compatible so the same code should work in v2 without any change

**Comment by adderly** [comment]
This fixes the drawer swipe on IOS.

**Comment by Romick2005** [comment]
Update as for today close outside works as expected. Drawer swipe does not work only in debug mode.

**Comment by Winglonelion** [comment]
@Romick2005 Great works! 💯  But the main brain goes so far, could you resolve conflict?

**Comment by Romick2005** [comment]
> @Romick2005 Great works! 💯 But the main branch goes so far, could you take a look to resolve conflict?

Done.

**Comment by JohnBerd** [comment]
Thank you for this great job @Romick2005. Really need this to be merged, would it be a lot of work to get the code approval?

**Comment by kg-currenxie** [comment]
Any news on this? 🤔

**Comment by satya164** [comment]
Hello, the PR got closed automatically due to some changes in the main branch. Would you be able to send a new PR? Thank you.

**Pull request closed without merging**
