### PR TITLE
fix(drawer): fix drawer when changing drawertype (ex: front -> permanent)

### PR DESCRIPTION
**Pull request by shrief1234567899**
regarding to 
https://github.com/react-navigation/react-navigation/issues/10210

and after latest updates for 
https://github.com/react-navigation/react-navigation/commit/524657484e6b21ecc5754b63468dd00304a8e450

### CODE REVIEW

**Comment by satya164** [comment]
What exactly is this fixing?

**Comment by sherif-cyber** [comment]
> What exactly is this fixing?

fixing white block in screen when
- open drawer as front drawerType
- switching from portrait to landscape mode
- change drawerType to be Permanent instead of front

**Comment by satya164** [comment]
I already made a fix in https://github.com/react-navigation/react-navigation/commit/524657484e6b21ecc5754b63468dd00304a8e450, what does this do additionally?

**Comment by sherif-cyber** [comment]
> I already made a fix in [5246574](https://github.com/react-navigation/react-navigation/commit/524657484e6b21ecc5754b63468dd00304a8e450), what does this do additionally?

i just changed **undefined transform** to be zero in translateX

because without this change, we still face an issue **(wrong position for drawer in middle of screen and white space beside it)** when changing drawerType within Runtime from **front** to be **permanent** as appeared in video.

**Comment by satya164** [comment]
> because without this change, we still face an issue (wrong position for drawer in middle of screen and white space beside it) when changing drawerType within Runtime from front to be permanent as appeared in video.

Can you open a new bug report for the issue you encountered?

> i just changed undefined transform to be zero in translateX

I can see that in the commit, but the mentioned commit (and the code comments) already say why I used `undefined` and not a transform. So just changing it to `transform` is not a fix.

**Comment by sherif-cyber** [comment]
> > because without this change, we still face an issue (wrong position for drawer in middle of screen and white space beside it) when changing drawerType within Runtime from front to be permanent as appeared in video.
> 
> Can you open a new bug report for the issue you encountered?
> 
> > i just changed undefined transform to be zero in translateX
> 
> I can see that in the commit, but the mentioned commit (and the code comments) already say why I used `undefined` and not a transform. So just changing it to `transform` is not a fix.

umm, i removed using translateX and now i am using empty array instead of it, and it's also working fine for me.

when we use undefined it cause a design bug **(same bug in mentioned video)**

**Comment by sherif-cyber** [comment]
> > > because without this change, we still face an issue (wrong position for drawer in middle of screen and white space beside it) when changing drawerType within Runtime from front to be permanent as appeared in video.
> > 
> > 
> > Can you open a new bug report for the issue you encountered?
> > > i just changed undefined transform to be zero in translateX
> > 
> > 
> > I can see that in the commit, but the mentioned commit (and the code comments) already say why I used `undefined` and not a transform. So just changing it to `transform` is not a fix.
> 
> umm, i removed using translateX and now i am using empty array instead of it, and it's also working fine for me.
> 
> when we use undefined it cause a design bug **(same bug in mentioned video)**

can we merge it ? @satya164

**Comment by adamhari** [comment]
I've been locked to 6.1.4 because the changes in 6.1.5 broke the drawer like this when switching the drawerType. This PR fixes it for me.

**Review by satya164 — APPROVED** [review]
Can confirm `[]` fixes the issue. thank you

**Pull request merged**
