### PR TITLE
fix: fix ignored defaultOptions prop

### PR DESCRIPTION
**Pull request by heecheolman**
Change the createNativeStackNavigator 's defaultScreenOptions correctly so that it can be provided.

**Motivation**

#### 2.  Even if you don't provide defaultScreenOptions , you pass a rest prop to NativeStackView , but NativeStackView doesn't actually set defaultScreenOptions .

```ts
// packages/native-stack/src/views/NativeStackView.tsx
export default function NativeStackView({ state, descriptors }: Props) {
 // ...
}
```

> https://github.com/react-navigation/react-navigation/blob/main/packages/native-stack/src/views/NativeStackView.tsx#L34

**Test plan**

A look at the mergedOptions difference
```tsx
const Stack = createNativeStackNavigator();

function Page() {
  return (
  <NavigationContainer>
    <Stack.Navigator 
      defaultScreenOptions={{
        headerTitleAlign: 'left',
      }}
      screenOptions={{
        headerTitle: 'Hello World',
      }}
    >
       {/* Screens */}
    </Stack.Navigator>
  </NavigationContainer>
}
```

#### As-Is: 
defaultScreenOptions and screenOptions are not merged.

[mergedOptions Output:](https://github.com/react-navigation/react-navigation/blob/main/packages/core/src/useDescriptors.tsx#L185) 
```
{"mergedOptions": {"headerTitleAlign": "left"}}
```

#### To-Be: 

[mergedOptions Output:](https://github.com/react-navigation/react-navigation/blob/main/packages/core/src/useDescriptors.tsx#L185) 
```
{"mergedOptions": {"headerTitle": "Hello World", "headerTitleAlign": "left"}}
```

---

If you say that your intention is not to set defaultScreenOptions, please explain in the comments. :)

### CODE REVIEW

**Comment by satya164** [comment]
There's no `defaultScreenOptions` prop documented for navigators. It's intended be **passed by navigators** to `useNavigationBuilder`.

**Comment by heecheolman** [comment]
@satya164 
>There's no defaultScreenOptions prop documented for navigators. It's intended be passed by navigators to useNavigationBuilder.

As you said, it is not in the documentation, but if you look at Type, there is defaultOptions.

If providing defaultOptions is not the intention, the Navigator returned by createNativeStackNavigator should not have defaultOptions.

* [NativeStackNavigatorProps](https://github.com/react-navigation/react-navigation/blob/main/packages/native-stack/src/types.tsx#L499)
* [DefaultNavigatorOptions](https://github.com/react-navigation/react-navigation/blob/main/packages/core/src/types.tsx#L59)

**Comment by satya164** [comment]
> the Navigator returned by createNativeStackNavigator should not have defaultOptions

Yes, it shouldn't have the type. PR to fix it is welcome.

**Comment by pfcodes** [comment]
> @satya164
> 
> > There's no defaultScreenOptions prop documented for navigators. It's intended be passed by navigators to useNavigationBuilder.
> 
> As you said, it is not in the documentation, but if you look at Type, there is defaultOptions.
> 
> If providing defaultOptions is not the intention, the Navigator returned by createNativeStackNavigator should not have defaultOptions.
> 
> * [NativeStackNavigatorProps](https://github.com/react-navigation/react-navigation/blob/main/packages/native-stack/src/types.tsx#L499)
> * [DefaultNavigatorOptions](https://github.com/react-navigation/react-navigation/blob/main/packages/core/src/types.tsx#L59)

This threw me off too

**Pull request closed without merging**
