### PR TITLE
Currently a user can double click on a button while an animation is i…

### PR DESCRIPTION
**Pull request by ghuh**
Currently a user can double click on a button while an animation is in progress resulting in the same navigation call getting triggered twice.  This prevents duplicate navigation to the same route.

### CODE REVIEW

**Comment by dantman** [comment]
-1 #135 has some other ideas on how to solve this issue, and this PR would break react-navigation in some cases

This PR rejects all actions where `routeName` matches the current `routeName` whether unintentional or intentional. (and seems to do it across multiple levels of navigator)

However there are a wide variety of situations where an app may intentionally desire navigating to another route with the same name, notably the same routeName but different params. eg: You're on `{ routeName: 'Profile', params: { user: 'Alice' } }` and a friend link to "Bob" wants to navigate to `{ routeName: 'Profile', params: { user: 'Bob' } }`. This PR would reject that.

**Comment by ghuh** [comment]
It looks like #135 is a lot of talk without anything happening.  I'd be happy to close this PR if there is another solution incoming.

If not, I'd be happy to add support for checking params.  That is easy enough to do.

Let me know what you guys are planning.

**Comment by dantman** [comment]
Checking for params just sounds like stacking a hack on top of another hack to work around the flawed nature of the hack. You're now doing a shallow/deep comparison of objects (which this lib doesn't do) just to work around something that there are better ways of handling.

If you want to work around this now, you don't even need any changes to react-native. Just set a `this._lock = true;` in your event handler when you make the navigate call, reject any events while `this._lock` is true, and unset that after a few seconds. Or use a debounce function from a library like lodash.

**Comment by ghuh** [comment]
I agree that this is a hack solution.  However, having to do tracking of `this._lock = true` outside of `react-navigation` is also a hack (a worse one in my opinion).  This issue should be handled inside the library.

I'll leave this PR open for now so that others may reference it until a more elegant solution is implemented.

**Comment by matthamil** [comment]
I'm going to mark this PR as "On Hold" for now. There has been discussion on this enhancement at https://github.com/react-community/react-navigation/issues/135, https://github.com/react-community/react-navigation/issues/271, and https://github.com/react-community/react-navigation/pull/1787. I think that this is a much needed part of the library; however, we should be careful to accept any "hack" solutions. A hack is better than no solution, in my opinion, but I'm curious what you think @skevy

**Comment by ghuh** [comment]
Yeah, I've been following some of the other discussions and I 100% agree that this should not be merged.  There are much better solutions coming.

**Comment by brentvatne** [comment]
you can handle this now with idempotent pushes, still need to write up docs here: https://github.com/react-navigation/react-navigation.github.io/issues/42 though!

`this.props.navigation.navigate({routeName: 'yourRoute', key: 'pick-a-key'});` -- it will only navigate to that once (based on key) regardless of how many times you fire it

**Pull request closed without merging**
