### PR TITLE
flow cover for getActiveChildNavigationOptions

### PR DESCRIPTION
**Pull request by Preeternal**
## Motivation

Try to solve the issue - https://github.com/react-navigation/react-navigation/issues/6002#issuecomment-502908696

### CODE REVIEW

**Comment by Ashoat** [comment]
Check the example usage in #6002 - you should be using `NavigationScreenProp`, not `NavigationProp`

**Comment by Preeternal** [comment]
Thanks for review. Seems it works as expected. Could you please check it too?

**Comment by Ashoat** [comment]
The sounds wrong, `NavigationParams` is not the same as "navigation options"

**Comment by Preeternal** [comment]
typescript defs from the RNN sources:

`  // @todo - any..
  export function getActiveChildNavigationOptions<S>(
    navigation: NavigationProp<S>,
    screenProps?: ScreenProps
  ): NavigationParams;`

**Comment by Ashoat** [comment]
Awesome, thanks! Next step is to get these changes onto `flow-typed`. You'll need to add your new code to the [libdef for `react-navigation`](https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/react-navigation_v3.x.x/flow_v0.92.x-/react-navigation_v3.x.x.js) as well as [`@react-navigation/core`](https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/%40react-navigation/core_v3.x.x/flow_v0.92.x-/core_v3.x.x.js).

**Comment by Preeternal** [comment]
Thanks. Could you please take a look https://github.com/flow-typed/flow-typed/pull/3448

**Pull request merged**
