### PR TITLE
feat: implement usePreventRemove hook

### PR DESCRIPTION
**Pull request by kacperkapusciak**
As we still polishing the API we're marking the hook for now as `UNSTABLE_usePreventRemove`. 

**Motivation**

This PR intruduces a new hook - `usePreventRemove` -  used for preventing going back in `react-navigation`.  This hook would allow to support preventing of screen removal in `@react-navigation/native-stack` which is one of [the limitations](https://reactnavigation.org/docs/preventing-going-back/#limitations) of current API.

The `usePreventRemove` hook would take two arguments:

- `preventRemove` - boolean indicating whether to prevent screen from being removed
- `callback` - optional function which is executed when screen was prevented from being removed

**Example use case**

```jsx
function EditText({ navigation }) {
  const [text, setText] = React.useState('');
  const hasUnsavedChanges = Boolean(text);

  usePreventRemove(hasUnsavedChanges, (data) => {
    Alert.alert(
      'Discard changes?',
      'You have unsaved changes. Discard them and leave the screen?',
      [
        { text: "Don't leave", style: 'cancel', onPress: () => {} },
        {
          text: 'Discard',
          style: 'destructive',
          onPress: () => navigation.dispatch(data.action),
        },
      ]
    );
  });

  return (
    <TextInput
      value={text}
      placeholder="Type something…"
      onChangeText={setText}
    />
  );
}
```

<details>
<summary>Example code to test the change</summary>
<br>

```tsx
import {
  NavigationContainer,
  usePreventRemove,
} from '@react-navigation/native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import { createStackNavigator } from '@react-navigation/stack';
import * as React from 'react';
import { Button, Text, View } from 'react-native';

function HomeScreen({ navigation }: any) {
  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Text>Home Screen</Text>
      <Button
        title="Go to Details"
        onPress={() => navigation.navigate('Details')}
      />
    </View>
  );
}

function DetailsScreen({ navigation }: any) {
  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Text>Details Screen</Text>
      <Button
        title="Go to Nested"
        onPress={() => navigation.navigate('Nested')}
      />
    </View>
  );
}

function SettingsScreen({ navigation }: any) {
  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Text>Settings Screen</Text>
      <Text>PREVENTED FROM REMOVAL</Text>
      <Button
        title="Go to Profile"
        onPress={() => navigation.navigate('Profile')}
      />
      <Button
        title="Go back to Home"
        onPress={() => navigation.navigate('Home')}
      />
    </View>
  );
}

function ProfileScreen({ navigation }: any) {
  usePreventRemove(true);

  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Text>Profile Screen</Text>
      <Button
        title="Go to Another"
        onPress={() => navigation.navigate('Another')}
      />
    </View>
  );
}

function AnotherScreen({ navigation }: any) {
  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Text>Another Screen</Text>
      <Button
        title="Go back to Home"
        onPress={() => navigation.navigate('Home')}
      />
    </View>
  );
}

const Stack = createNativeStackNavigator();
const NestedStack = createNativeStackNavigator();

function MyNestedStack() {
  return (
    <NestedStack.Navigator>
      <NestedStack.Screen name="Settings" component={SettingsScreen} />
      <NestedStack.Screen name="Profile" component={ProfileScreen} />
      <NestedStack.Screen name="Another" component={AnotherScreen} />
    </NestedStack.Navigator>
  );
}

function App() {
  return (
    <NavigationContainer>
      <Stack.Navigator initialRouteName="Home">
        <Stack.Screen name="Home" component={HomeScreen} />
        <Stack.Screen name="Details" component={DetailsScreen} />
        <Stack.Screen name="Nested" component={MyNestedStack} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}

export default App;

```

</details>

### CODE REVIEW

**Review by satya164 — APPROVED** [review]

**Comment by GaylordP** [comment]
Thank you very much for this feature! @kacperkapusciak  :)

Do you have an approximate release date in the next version @satya164  ?

Thanks you :)

**Comment by hotaryuzaki** [comment]
how to use this function in class component????
is there any API has same function

**Comment by hotaryuzaki** [comment]
> how to use this function in class component???? is there any API has same function

I create new component like this
```
import { UNSTABLE_usePreventRemove } from "@react-navigation/native";

const BackHandlerIos = ({ enable, callback }) => {
  // PREVENT SWIPE BACK, ALTERNATIVE FOR BACKHANDLER IN IOS
  UNSTABLE_usePreventRemove(enable, () => {
    callback();
  });

  return null;
}

export default BackHandlerIos;
```

then i called like this
```
constructor(props) {
  super(props);
  this.state = {
    preventRemove: true
  };
}

const _handleBackButton = () => {
    this.setState({ preventRemove: false }); // TO ENABLE BACK TO PREVIOUS SCREEN

    Alert.alert(
      `Batal Edit`,
      `Apakah Anda yakin untuk membatalkan?`,
      [
        {
          text: "OK",
          onPress: () => this.props.navigation.goBack(),
        },
        {
          text: "Batal",
          onPress: () => this.setState({ preventRemove: true }) // TO DISABLE BACK TO PREVIOUS SCREEN
        },
      ]
    );
};

render() {
  return (
    <BackHandlerIos enable={preventRemove} callback={_handleBackButton} />
  );
}
```

**Comment by mrboomer** [comment]
I did something a bit similar:

```
const [text, setText] = useState('');
const [preventRemove, setPreventRemove] = useState(false);

const hasUnsavedChanges = Boolean(text);

useEffect(() => {
  setPreventRemove(hasUnsavedChanges);
}, [hasUnsavedChanges]);

UNSTABLE_usePreventRemove(preventRemove, () => {
  Alert.alert(
    'Discard changes?',
    'You have unsaved changes. Are you sure to discard them and leave the screen?',
    [
      {text: "Don't leave", style: 'cancel', onPress: () => {}},
      {
        text: 'Discard',
        style: 'destructive',
        onPress: () => {
          setPreventRemove(false);
          props.navigation.goBack();
        },
      },
    ],
  );
});
```

**Comment by Wenceslauu** [comment]
does it work for both android and ios?

**Comment by hotaryuzaki** [comment]
> does it work for both android and ios?

This issue is iOS only, because for Android you can use BackHandler in react native with more flexible functionality.

**Pull request merged**
