### PR TITLE
Add expo to NavigationPlayground

### PR DESCRIPTION
**Pull request by brunohkbx**
## Test plan

1. Download this branch
2. Navigate to `examples/NavigationPlayground` and install packages `yarn`
3. Run `yarn start`
4. Open app on expo

### CODE REVIEW

**Comment by brunohkbx** [comment]
Could someone review the jest configuration? I'm getting the following error without a4fc152 

```
yarn run v1.13.0-20181121.1436
warning ../../../../package.json: No license field
$ jest && tsc
 FAIL  ./App.test.tsx
  ✕ renders without crashing (26ms)

  ● renders without crashing

    TypeError: Cannot read property 'default' of undefined

      at new KeyboardAwareNavigator (node_modules/react-navigation/node_modules/@react-navigation/native/dist/createKeyboardAwareNavigator.js:4:527)
      at constructClassInstance (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:4810:18)
      at updateClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6579:5)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7413:16)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10138:12)
      at workLoop (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10170:24)
      at renderRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10256:7)
      at performWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11121:7)
      at performWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11033:7)
      at performSyncWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11007:3)

  console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8060
    The above error occurred in the <KeyboardAwareNavigator> component:
        in KeyboardAwareNavigator (at createAppContainer.js:325)
        in NavigationContainer (created by App)
        in App
    
    React will try to recreate this component tree from scratch using the error boundary you provided, NavigationContainer.

  console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8060
    The above error occurred in the <NavigationContainer> component:
        in NavigationContainer (created by App)
        in App
    
    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        2.587s
Ran all test suites.
```

**Comment by brentvatne** [comment]
thanks! don't have time to look at this right now, if @satya164 does that'd be cool otherwise it might take me a couple of weeks

**Comment by satya164** [comment]
> Could someone review jest's configuration? I'm getting the following error without a4fc152

Regarding the tests, I ran the tests and they still fail with a different error. I'd say lets just remove the tests under the `example`. They don't test anything and it's unlikely that we're going to add anything there.

**Comment by brunohkbx** [comment]
@satya164 thanks for the review! 
It's done. I had to modify the CI config, could you check it? 579f572e4e69a5e57fb4ee46557321afb730d431

**Pull request merged**
