### PR TITLE
fix: let Bottom Tabs accessibility labels generated by the OS

### PR DESCRIPTION
**Pull request by MoOx**
The accessibility label "tab X of Y" is generated by the os, with the proper language. In order to do so, we need the OS to detect tab inside a tablist. This PR should handle this.
It can be tested on iOS via VoiceOver. Pressing a tab should say "{label}, tab X on Y".

### CODE REVIEW

**Review by satya164 — APPROVED** [review]
Thanks!

**Comment by MoOx** [comment]
Don't be too grateful, it doesn't work as expected. I am trying to track down the issue with react native, but my understanding is that react native doesn't properly inform iOS about accessibility traits (even if the doc say so).
I will let this PR open in case I found something to adjust this.

**Comment by satya164** [comment]
@MoOx that's sad to know. lemme know if you figure it out and i'll be happy to merge.

**Comment by satya164** [comment]
Closing due to cleanup PRs. Please send a new PR if you manage to find a solution.

**Pull request closed without merging**
