### PR TITLE
fix: drawer position on window resize

### PR DESCRIPTION
**Pull request by kateinkim**
I recently ran into a similar issue to #8551. When digging into the drawer navigator source I noticed that it's using `useSafeAreaFrame` and that it wasn't updating dimensions upon window resize. I switched to using `useWindowDimensions` and it started updating dimensions on resize fixing my issue. I'm not sure if there is some reason I'm missing for using `useSafeAreaFrame` over `useWindowDimensions` here but I do think this is the core issue with drawer position on web when resizing the window.

|Before|After|
|-|-|
|<video src="https://github.com/react-navigation/react-navigation/assets/53795920/4e0e7266-ab12-48f1-a12d-457f8c5945ad">|<video src="https://github.com/react-navigation/react-navigation/assets/53795920/1d827f3a-f5cc-4030-b30e-e966a63b2771">|

|

### CODE REVIEW

**Comment by avet-m** [comment]
@satya164 @osdnk please have a look, this workaround works pretty well. It is necessary for Web projects.

**Comment by CasuallyCaffeinated** [comment]
Can we get an update on this? This would be a great fix to add since on web currently, the RN drawer is utterly broken when resizing the screen

**Comment by claudesortwell** [comment]
@CasuallyCaffeinated @avet-m, and anyone else. Here is a patch package for the above fix.

`@react-navigation+drawer+6.6.6.patch`
```patch
diff --git a/node_modules/@react-navigation/drawer/lib/commonjs/views/DrawerView.js b/node_modules/@react-navigation/drawer/lib/commonjs/views/DrawerView.js
index 58a6c69..4a4ec73 100644
--- a/node_modules/@react-navigation/drawer/lib/commonjs/views/DrawerView.js
+++ b/node_modules/@react-navigation/drawer/lib/commonjs/views/DrawerView.js
@@ -81,7 +81,7 @@ function DrawerViewBase(_ref2) {
   if (!loaded.includes(focusedRouteKey)) {
     setLoaded([...loaded, focusedRouteKey]);
   }
-  const dimensions = (0, _reactNativeSafeAreaContext.useSafeAreaFrame)();
+  const dimensions = (0, _reactNative.useWindowDimensions)();
   const {
     colors
   } = (0, _native.useTheme)();
diff --git a/node_modules/@react-navigation/drawer/lib/module/views/DrawerView.js b/node_modules/@react-navigation/drawer/lib/module/views/DrawerView.js
index 38765bb..1875752 100644
--- a/node_modules/@react-navigation/drawer/lib/module/views/DrawerView.js
+++ b/node_modules/@react-navigation/drawer/lib/module/views/DrawerView.js
@@ -2,9 +2,8 @@ function _extends() { _extends = Object.assign ? Object.assign.bind() : function
 import { getHeaderTitle, Header, SafeAreaProviderCompat, Screen } from '@react-navigation/elements';
 import { DrawerActions, useTheme } from '@react-navigation/native';
 import * as React from 'react';
-import { I18nManager, Platform, StyleSheet, View } from 'react-native';
+import { I18nManager, Platform, StyleSheet, useWindowDimensions, View } from 'react-native';
 import * as Reanimated from 'react-native-reanimated';
-import { useSafeAreaFrame } from 'react-native-safe-area-context';
 import { addCancelListener } from '../utils/addCancelListener';
 import DrawerPositionContext from '../utils/DrawerPositionContext';
 import DrawerStatusContext from '../utils/DrawerStatusContext';
@@ -72,7 +71,7 @@ function DrawerViewBase(_ref2) {
   if (!loaded.includes(focusedRouteKey)) {
     setLoaded([...loaded, focusedRouteKey]);
   }
-  const dimensions = useSafeAreaFrame();
+  const dimensions = useWindowDimensions();
   const {
     colors
   } = useTheme();

```

**Comment by CasuallyCaffeinated** [comment]
@claudesortwell Thanks for the info! I went ahead and implemented that change, but it seems to only fix the issues when node ENV is in `development`. I suspect it has something to do with the way Webpack bundles these changes in a production ENV, but I must admit it's a bit of an unknown for me. Regardless, changing those files doesn't solve the issue in prod. Have you encountered anything like that?

**Comment by avet-m** [comment]
@claudesortwell Here is an another patch, I faced with an issue on Android with notch, where **useWindowDimensions** is not always works well. So better keep both hooks and use them depends on OS. 

`@react-navigation+drawer+6.6.6.patch`

```patch
diff --git a/node_modules/@react-navigation/drawer/lib/module/views/DrawerView.js b/node_modules/@react-navigation/drawer/lib/module/views/DrawerView.js
index 38765bb..4e848e4 100644
--- a/node_modules/@react-navigation/drawer/lib/module/views/DrawerView.js
+++ b/node_modules/@react-navigation/drawer/lib/module/views/DrawerView.js
@@ -2,7 +2,7 @@ function _extends() { _extends = Object.assign ? Object.assign.bind() : function
 import { getHeaderTitle, Header, SafeAreaProviderCompat, Screen } from '@react-navigation/elements';
 import { DrawerActions, useTheme } from '@react-navigation/native';
 import * as React from 'react';
-import { I18nManager, Platform, StyleSheet, View } from 'react-native';
+import { I18nManager, Platform, StyleSheet, View, useWindowDimensions } from 'react-native';
 import * as Reanimated from 'react-native-reanimated';
 import { useSafeAreaFrame } from 'react-native-safe-area-context';
 import { addCancelListener } from '../utils/addCancelListener';
@@ -72,7 +72,7 @@ function DrawerViewBase(_ref2) {
   if (!loaded.includes(focusedRouteKey)) {
     setLoaded([...loaded, focusedRouteKey]);
   }
-  const dimensions = useSafeAreaFrame();
+  const dimensions = Platform.OS === 'web' ? useWindowDimensions() : useSafeAreaFrame();
   const {
     colors
   } = useTheme();
```

**Pull request closed without merging**
