### PR TITLE
Fix issue undefined is not an object evaluating r.default

### PR DESCRIPTION
**Pull request by ebaynaud**
Fix https://github.com/aksonov/react-native-router-flux/issues/3124

Please provide enough information so that others can review your pull request:

## Motivation

Release builds fails without these changes

## Test plan

No more errors

## Code formatting

Simple letter put from uppercase to lowercase

## Changelog

Not required I guess

### CODE REVIEW

**Comment by ericvicenti** [comment]
I'm confused why this would fix anything.. what bundler are you using?

**Comment by ebaynaud** [comment]
Standard metro bundler... I do not know what really happens as you can see in https://github.com/aksonov/react-native-router-flux/issues/3124 but what I'm sure of is that it fixes the encountered issue for me and other people!

**Comment by brentvatne** [comment]
thanks for submitting a pr! although this seems to fix your problem, i'm hesitant to land something that works without any reason that anyone can understand. it seems more like a bug in another tool.

**Comment by ebaynaud** [comment]
I understand @brentvatne but it's a really minor change that could avoid me and others folks still using react-native-router-flux to fork react-navigation. That's the only workaround found yet...

**Comment by brentvatne** [comment]
sorry unless someone can explain why this fixes the problem we cannot land it. the diff on its own makes no sense

**Comment by TwilightOwl** [comment]
@brentvatne  https://babeljs.io/docs/en/babel-plugin-transform-class-constructor-call
This babel plugin is removed from babel 7, therefore your module doesn't work in React Native 0.56 in some cases. Now creating instance without 'new' keyword is impossible. So use 'tabRouter' instead 'TabRouter' or use new with 'TabRouter'

**Comment by martincarrera** [comment]
Please @brentvatne could you reopen this PR? Thanks.

**Comment by brentvatne** [comment]
thanks! yes

**Comment by rishiankush** [comment]
I updated my react-navigation package with this above fix in all the files:
src/navigators/DrawerNavigator.js
src/navigators/StackNavigator.js
src/navigators/TabNavigator.js

but still getting the same issue in release mode:
`Unhandled JS Exception: TypeError: undefined is not an object (evaluating 'r.default')`

**Comment by brentvatne** [comment]
cc @ebaynaud

**Comment by warlock1024127** [comment]
I solved the same issue by: https://github.com/facebook/react-native/issues/20150, Workaround 2

**Comment by abartolo** [comment]
@ebaynaud Thanks for the fix. I am now able to compile release build successfully.

@rishiankush Did you update all files? I see 4 files are changed but you only mentioned 3.

cc: @brentvatne

**Comment by brentvatne** [comment]
if someone can confirm that this works as expected i can land it and publish an update to 1.x

**Comment by abartolo** [comment]
@brentvatne I can confirm this is working. I have been building release builds for IOS and Android using the following "git+https://github.com/ebaynaud/react-navigation#1.x" in my package.json for about 3 weeks now.

**Comment by brentvatne** [comment]
please create a new issue and follow the template @luco

**Pull request merged**
