### PR TITLE
fix: replace series function used to queue async callbacks

### PR DESCRIPTION
**Pull request by karlsander**
**Motivation**

This function is used to ensure that all state change callbacks to sync the local browser history state run in series. The functions are async because `history.go` is not a synchronous function.

I noticed that in chrome, the URL was updating to the previous url instead of the new one in some navigations and tracked it down to the fact that the `history.go` navigation takes longer than in other browsers. This function is supposed to mitigate that, but I believe it has a bug. The function will not properly return early, because the finally clause will still always run and immediately reset the `isRunning` state. Even after fixing this, the function didn't quite work right for queuing more than two callbacks.

I have replaced the function with a simpler implementation that does the same task.

**Test plan**

Describe the **steps to test this change** so that a reviewer can verify it. Provide screenshots or videos if the change affects UI.

The change must pass lint, typescript and tests.

### CODE REVIEW

**Review by satya164 — APPROVED** [review]
Thanks for the PR

**Comment by satya164** [comment]
This change seems to break unit tests. Can you take a look?

**Comment by karlsander** [comment]
I'm not sure exactly, but the test is failing on `main` for me in the same way. I think it is addressed here? https://github.com/react-navigation/react-navigation/pull/11509

**Comment by mountiny** [comment]
@karlsander Would you be able to merge main to your branch? The tests are passing on main

**Comment by adamgrzybowski** [comment]
Hey, @karlsander I've tried wrapping `expect` with `waitFor` and tests seem to work fine. Here's how it looks. https://gist.github.com/adamgrzybowski/7839818fb1a9728052bab0a1d84464e4

There's one thing I'm not 100% sure of. I had to remove `is.useFakeTimers()` but the tests still passed.

**Comment by adamgrzybowski** [comment]
@karlsander Hey I created a [PR](https://github.com/react-navigation/react-navigation/pull/11565) to test new tests for the series without distracting you if something went wrong 😄 

I've used `await` and it seems to work fine. I've also checked with the debugger and the value for `window.location.pathname` matches the expected value.

BTW we used your `series` implementation as a patch in our app and it seems to solve one problem that we had so I think you did a good job with this solution

BTW_2.0 the old implementation of `series` is probably broken because of the `try {...} finally {...}` blocks. If we remove them the result is the same as with your simpler implementation (the problem in our app is fixed and the tests fail)

The `finally` block is executed even if you return in `try` and that breaks the queue. At least that's my guess

**Comment by karlsander** [comment]
> BTW_2.0 the old implementation of series is probably broken because of the try {...} finally {...} blocks. If we remove them the result is the same as with your simpler implementation (the problem in our app is fixed and the tests fail)

I don't remember exactly, but I think in that case two async functions at the same time are queued correctly, but not 3+ (a situation that doesn't really happen in this usage anyway).

**Comment by karlsander** [comment]
@satya164 all looks green now, but I cannot merge because I don't have access

**Comment by osdnk** [comment]
@adamgrzybowski @karlsander I guess that is safe to go?

**Comment by mountiny** [comment]
I think so, we are using it in our App without any issues found so far 🤞 https://github.com/Expensify/App/pull/25989/files

**Comment by karlsander** [comment]
We are also using the patch with success, would appreciate if we can get this merged.

**Pull request merged**
