### PR TITLE
Factor out DrawerItem for easy "account picker" demo

### PR DESCRIPTION
**Pull request by cooperka**
## Motivation

To make it easy to do things like this:

<div>

</div>

And this:

<div>

</div>

## Changes

1. Factor out `DrawerNavigatorItem` into its own component
2. Add an `itemComponent` prop to [`contentOptions`](https://reactnavigation.org/docs/navigators/drawer#contentOptions-for-DrawerItems) (default is `DrawerNavigatorItem`)
3. Allow the `onPress` handler to be `null` to remove touch feedback
4. Update the NavigationPlayground Drawer example to show off the account picker

No breaking changes, as far as I know.

## Usage

See the changes to the demo app for an implementation example.

## Test Plan

You'll probably want to rebase locally on https://github.com/react-community/react-navigation/pull/2170 so that the example app works (verified no conflicts, easy rebase). It also depends on the fix in https://github.com/react-community/react-navigation/pull/2180.

1. Run the NavigationPlayground app
2. Tap the Drawer Example and try it out

Please let me know what you think; the API makes sense to me but I'm open to changing it.

## Notes

Originally submitted as https://github.com/react-community/react-navigation/pull/1317, but due to other PRs that have been merged, the logic has changed significantly enough to warrant opening a separate PR.

### CODE REVIEW

**Comment by wilomgfx** [comment]
can we get this merged or no ?

**Comment by cooperka** [comment]
@wilomgfx I hope so! The devs are currently pretty swamped, so if you want to use this in your app right now you should fork the library. It will likely be a while before the devs can get around to merging this.

**Comment by ericvicenti** [comment]
Hi folks, we are trying to remove complexity from the core library and encourage more third party navigators to support various use cases. With that in mind, I'm going to close this out

I think the drawer project should be owned by some of you who use it in your apps, because you'll know how it should be improved. @cooperka, are you possibly interested in launching a separate package for the drawer navigator? I would help you get started, and we would remove the drawer from this core library, and encourage people to use yours.

If anybody else is interested in helping out with the drawer, in any way, please reach out to me on GH or twitter!

**Comment by cooperka** [comment]
I would be happy to help contribute to a community project, but unfortunately I don't have the time right now to take the lead on this. Thank you for the update!

**Comment by ericvicenti** [comment]
No worries, hopefully the project will started soon and there will be a more focused team for you to send your drawer PRs to 😆

**Comment by cooperka** [comment]
I've come back from the future to recommend the Material Design "Paper" [drawer items](https://callstack.github.io/react-native-paper/drawer-item.html) for anyone who wants this behavior in their app as mentioned here: https://github.com/react-navigation/react-navigation/pull/2180#issuecomment-366739840.

**Pull request closed without merging**
