### PR TITLE
Create CHANGELOG.md

### PR DESCRIPTION
**Pull request by rodrigobdz**
List all changes between versions to notify about notable changes in releases. 
PR for #3948 and #4512.

### CODE REVIEW

**Comment by brentvatne** [comment]
out of curiosity, what's wrong with https://github.com/react-navigation/react-navigation/releases?

**Comment by rodrigobdz** [comment]
The main issue I see with the current workflow is that **you** have to **manually** dig into the commit history after each release to generate the release notes. Thus, you end up releasing a version with no further details until you are done summarizing the changes which leads to #4002 and [#806](https://github.com/react-navigation/react-navigation/issues/806). 

As opposed to keeping a changelog which includes an **Unreleased** section where contributors provide a description of the changes made to the codebase together with the PR. See [react_on_rails](https://github.com/shakacode/react_on_rails/blob/94366056a63b0ef340dccd810734a8791806257b/CONTRIBUTING.md#summary)'s workflow.

**Comment by brentvatne** [comment]
Sure let's give it a try

**Comment by brentvatne** [comment]
Updated the PR template to add changelog requirement: https://github.com/react-navigation/react-navigation/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by rodrigobdz** [comment]
Looks good to me. I just fixed a typo in the pull request template in PR #4558.

**Comment by rodrigobdz** [comment]
@brentvatne It's been almost a month since the CHANGELOG.md creation. How is it working for you?
I see that contributors have been actively taking care of the changelog.
https://github.com/react-navigation/react-navigation/pull/4701/files

**Comment by rodrigobdz** [comment]
>@rodrigobdz - I think it was a nice improvement! I like having all of the notes in a single file compared to paginated in the releases tab. thanks!

@brentvatne Glad you liked it!

**Pull request merged**
