### PR TITLE
fix(drawer): Handle right side drawer not fully hidden

### LINKED ISSUE #10335: Right side drawer not fully hidden when closed
### Current behavior

When the drawer is on the right and closed it is still visible by I assume 20% of the width of the screen.

Screen Shot 2022-02-08 at 11 17 42 PM

Screen Shot 2022-02-08 at 11 17 35 PM

### Expected behavior

Should be hidden when closed

### Reproduction

https://github.com/jcgertig/rnn-drawer-issue

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |  6.0.8
| @react-navigation/drawer               | 6.3.1
| @react-navigation/native-stack         | 6.5.0
| react-native-safe-area-context         | 3.3.2
| react-native-screens                   | 3.10.2
| react-native-gesture-handler           | 1.10.3
| react-native-reanimated                | 2.4.1
| react-native                           | 0.67.2
| node                                   | 14.17.4
| yarn                            | 1.22.17

### PR DESCRIPTION
**Pull request by jcgertig**
Please provide enough information so that others can review your pull request:

**Motivation**

Fixes #10335

### CODE REVIEW

**Comment by jcgertig** [comment]
Bump

**Comment by jcgertig** [comment]
Bump

**Comment by SohelIslamImran** [comment]
Bump

**Comment by siarheipashkevich** [comment]
Bump

**Comment by jcgertig** [comment]
@satya164 can this please get reviews

**Comment by jcgertig** [comment]
@WoLewicki can someone please review this

**Comment by jcgertig** [comment]
@satya164 @WoLewicki  any movement?

**Comment by satya164** [comment]
I appreciate the PR but please stop pinging me. I have other work that I need to do and I'll review and merge when I get time. I don't need notifications every few days for every PR. You can use `patch-package` meanwhile in your project until it's merged.

**Comment by jcgertig** [comment]
I would have been fine but there have been other prs that came later that had interactions even just posting that it would be a bit before getting to it would have been enough. Leaving it for almost a whole month when it takes 10 seconds to just post that would be better.

**Comment by satya164** [comment]
> I would have been fine but there have been other prs that came later that had interactions 
> even just posting that it would be a bit before getting to it would have been enough

There are hundreds of PRs and issues. "even just posting" takes time. If I'm working for free on a project, I'll spend that time when I can. Just because I interacted with some other PR doesn't mean now I have to interact with every PR that's open.

> Leaving it for almost a whole month when it takes 10 seconds to just post that is not very nice.

And you can just use patch-package instead of pinging repeatedly. That's not very nice either and very inconsiderate of my time.

I posted because I got annoyed by repeated notifications, how does making me annoyed help your PR?

**Pull request closed without merging**
