### PR TITLE
Reset state instead of pushing new routes for navigation actions in Drawer

### PR DESCRIPTION
**Pull request by nico1510**
This pull request fixes the issue discovered by @vonovak here: https://github.com/react-community/react-navigation/pull/1914#issuecomment-325816788 and other users here https://github.com/react-community/react-navigation/issues/2883. Therefore @vonovak would be the perfect reviewer here ;)

The issue is the following: When nesting a StackNavigator with multiple screens inside a DrawerNavigator, the state of this StackNavigator is never reset. Instead the first route is pushed onto the existing Stack. Like @vonovak rightly described in the link I provided this is not ideal and the Stack of the StackNavigator should be reset instead.

### CODE REVIEW

**Comment by nico1510** [comment]
I just saw that there's also an issue for this: https://github.com/react-community/react-navigation/pull/3164

**Comment by nico1510** [comment]
@kelset could you please assign a different reviewer ? I don't think this is getting any attention

**Comment by kelset** [comment]
I hope you realise that this is an open source project, we maintainers can dedicate to it the spare time we have.

So it's really *not* appropriate to do comments like those. I'll remove him simply because I don't know who can pick it up.

**Comment by vonovak** [comment]
Hi, sorry for my silence. I just got back from a long vacation, and will be able to take a look at it later this week. If @nico1510 has a project that demonstrates the issue, that would help me a lot, since otherwise I'll have to create one by myself..?

**Comment by nico1510** [comment]
@kelset I hope you realize that I'm contributing to this in my spare time too ?! This comment was supposed to be a friendly proposal to change the reviewer since vovonak clearly doesn't seem to find the time (as you can read from his comment). I can't find something which is *not* appropriate about it !

@vonovak: I'll see if I can find the time to create an example

**Comment by vonovak** [comment]
This looks good to me. Note this resets the stack when leaving it, not when going to it, which is a good thing. Since the repo moved from react-community to react-navigation, I lost merge rights, but I will take care of merging this PR, thanks @nico1510 .

**Comment by nico1510** [comment]
and thank you for reviewing it @vonovak

**Comment by kelset** [comment]
@vonovak are you still able to review/approve PRs?

**Comment by vonovak** [comment]
@kelset I think everyone is able to review PRs, but only the "chosen ones" can merge :)

**Pull request merged**
