### PR TITLE
Bound correct context to 'navigationOptions' method

### PR DESCRIPTION
**Pull request by jneuendorf**
The component's `navigationOptions`-method's context (-> `this`) is now the component itself.
This allows calling other static methods from `navigationOptions`.

### CODE REVIEW

**Comment by satya164** [comment]
seems like it’ll be a source of confusion. in a static method, usually you’d expect `this` to refer to the class.

besides that, lots of beginners use React Navigation, so if they see they can use `this` to refer to the component in the function, they will also try to use that in methods of navigationOptions object

probably a better way is to pass the component instance as an argument

**Comment by jneuendorf** [comment]
Alright. Since you want to avoid confusion for people that are not only new to this library but to JavaScript as well I have no problem changing the code as you suggested.

**Comment by vonovak** [comment]
@jneuendorf hi, sorry, what exactly are you trying to achieve by this PR? What improvement does this bring? I need a little more context on this since the original description is outdated. Thanks

**Comment by jneuendorf** [comment]
@vonovak 

With ES6 there are static (or class) methods. As with any other object `this` always refers to the object the containing method was called on.

```javascript
class A {
  static property = 1
  static method() {
    return this.property + this.property
  }
}

console.log(A.method()) // == 2
```

### `navigationOptions` static method

In `react-navigation` the `navigationOptions` static method is passed around and called without any context - so `this === undefined`. But since it was defined as static method I would expect that `this` equals the class that it was defined in (or a subclass if `super` is used).
Keeping the correct context (`this` and `super`) is especially useful for

1. grouping complex and/or commonly used code into a separate function and
2. inheritance (-> avoiding code duplication across multiple classes).

Since this feature (-> context in static methods) is provided by the language it should work as intended (and should not be lost just because it's called by third-party code).

### Examples

regarding 1.

```javascript
class A extends React.Component {
  static _data = []

  static navigationOptions(props) {
    return {title: this.getHumanReadableDataHash()}
  }

  static getHumanReadableDataHash() {
    // crazy complicated algorithms going on here
    return this._data.map(/*...*/)reduce(/*...*/)
  }

  // This static method could be used by self-written code or even by another library.
  static verifyData(hash) {
    return this.getHumanReadableDataHash() === hash
  }
}
```

regarding 2.

```javascript
class DataScreen extends React.Component {
  static navigationOptions(props) {
    return {title: 'Data'}
  }
}

class UserDataScreen extends DataScreen {
  static navigationOptions(props) {
    return Object.assign(super.navigationOptions(props), {
      headerRight: <EditDataButton />,
    })
  }
}
```

**Comment by vonovak** [comment]
@jneuendorf I believe the answer you wrote describes the original code which was binding `this` to `Component`. Now the code is changed. I'd like to understand what the benefit is now. Why would I use the second parameter to `navigationOptions`?

ie. why write

```js
class A extends React.Component {
  static navigationOptions(props, ComponentClass) {
    return {title: ComponentClass.getHumanReadableDataHash()}
  }
}
```

instead of 

```js
class A extends React.Component {
  static navigationOptions(props) {
    return {title: A.getHumanReadableDataHash()}
  }
}
```

? Thanks!

**Comment by jneuendorf** [comment]
@vonovak The changed code you're talking about (b57e3e4b6c1165f5316be2b533da22d1771c96dd) was a reaction to satya164's [comment](https://github.com/react-community/react-navigation/pull/2990#issuecomment-345426676). Passing the class as argument or having the correct `this` is just a matter of taste (I believe).

Therefore, the question is

why write

```javascript
class A extends React.Component {
  static navigationOptions(props) {
    return {title: this.getHumanReadableDataHash()}
  }
}
```

instead of 

```javascript
class A extends React.Component {
  static navigationOptions(props) {
    return {title: A.getHumanReadableDataHash()}
  }
}
```

The answer is my 2nd example with some modifications and some additional explanation:

```javascript
```

**Comment by vonovak** [comment]
I see what you have in mind @jneuendorf 

I'll share my opinions regarding the example you gave:

1 . I'm not a fan of `class UserDataScreen extends DataScreen`. React in general favors composition over inheritance and I do not think we should deviate from that, ie. having "better inheritance" should not be a strong reason to add X to the library.

2 . `static heavyCalculationsWithLotsOfCode()` - if a function is placed on a component and is static, it may as well be placed independently (eg. in a separate module). This is not necessarily an argument against using `this.heavyCalculationsWithLotsOfCode()` and `super.heavyCalculationsWithLotsOfCode()` (but that approach makes use of the component-level inheritance that you've shown and I don't think we should go with) and I'm trying to say the logic can be placed somewhere else and accessed equally easily, without the need for inheritance on the component level. Also there is the confusion of what is `this` in the functions of `navgationOptions` as satya164 has mentioned.

So with this, I think it indeed is better to pass the component as the second argument, and I think we're back to the question I have asked in my previous post. We can already write 

```js
class A extends React.Component {
  static navigationOptions(props) {
    return {title: A.getHumanReadableDataHash()}
  }
}
```

so why pass the component in the second argument to `static navigationOptions`? I'm not a priori against it, but I like the fact that now there is one way to do this and it works. What are the reasons to add another one?

**Comment by satya164** [comment]
You can't call methods on the class instance, for example update some state on button press etc.

**Comment by vonovak** [comment]
@satya164 I'm not sure I'm following. Are you answering to the question "What are the reasons to add another one?"? This PR does not add the option to call methods on the class instance..

**Comment by satya164** [comment]
Yes it doesn't, so I don't see the point of the change. Here I commented to pass component instance which is a different thing https://github.com/react-navigation/react-navigation/pull/2990#issuecomment-345426676

**Comment by jneuendorf** [comment]
@vonovak I think not liking inheritance in the context of React is one thing but changing the language's behavior is another. Some people might still use inheritance even though the React community is not well-disposed towards it (however React itself provides an inheritance API via `React.Component`). One could of course write JS code in more functional way (point 2 of https://github.com/react-navigation/react-navigation/pull/2990#issuecomment-354197799) but I think using an object-oriented style should be fine due to the language's nature.

This discussion has cost a lot more time than the actual PR itself. So I suggest either closing the PR without merging or consider merging the initial commit 75d094be0791b6097f6c6fca6a379725924399bf because it's just 2 lines of code with quite an effect that don't really have any disadvantages (i.e. more flow type annotations) - if the commit is still up to date.

**Comment by brentvatne** [comment]
@jneuendorf - thank you for this thoughtful pr! I'm not convinced that we should add this to react-navigation at the moment -- it expands the api surface area slightly to support a use case that is primarily only useful when using component inheritance, which is not a pattern that we want to encourage in this library. additionally, in my opinion the above example can be re-written more clearly like this: 

```
class DataScreen extends React.Component {
  static navigationOptions(props) {
    return {title: this.heavyCalculationsWithLotsOfCode()}
  }

  static heavyCalculationsWithLotsOfCode() {
    // ...
    return 'heavyResult'
  }
}

class UserDataScreen extends React.Component {
  static navigationOptions(props) {
    return Object.assign(DataScreen.navigationOptions(props), {
      headerRight: <EditDataButton />,
    })
  }

  static heavyCalculationsWithLotsOfCode() {
    return DataScreen.heavyCalculationsWithLotsOfCode() + 'WithSomeExtendedBehavior'
  }
}
```

**Pull request closed without merging**
