### PR TITLE
Fix bug #3279 “Action within RESET doesn't trigger”

### PR DESCRIPTION
**Pull request by serhiipalash**
https://github.com/react-navigation/react-navigation/issues/3279

If you pass nested action within reset actions it has no effect.

| software         | version
| ---------------- | -------
| react-navigation | 1.1.2
| react-native     | 0.52

screen shot 2018-02-24 at 12 20 38 pm

Bug examples:
snack: https://snack.expo.io/H11t9nRvz
repo: https://github.com/serhiipalash/react-navigation-bug-3279-example

Bug screenshots:
when you press "Reset with nested action"

screen shot 2018-02-24 at 12 26 01 pm

you see new stack like there was no nested action

screen shot 2018-02-24 at 12 23 44 pm

Expected behaviour:
If I pass nested action within reset actions it should trigger changes in child router.

screen shot 2018-02-24 at 12 34 56 pm

Fix:

screen shot 2018-02-24 at 12 31 22 pm

Go to `fix-3279` branch in bug example repo to test this fix
https://github.com/serhiipalash/react-navigation-bug-3279-example/tree/fix-3279

### CODE REVIEW

**Comment by brentvatne** [comment]
- can you add test coverage for this?
- can you add an example to navigation playground that demonstrates this?

thanks!

**Comment by serhiipalash** [comment]
> can you add an example to navigation playground that demonstrates this?

@brentvatne do you have any instructions how to do it?

Isn't snack example not enough? 

> Bug examples:
snack: https://snack.expo.io/H11t9nRvz

**Comment by ericvicenti** [comment]
I do think we should have some tests for this, and also add it to the navigation playground so that we can test this ourselves in the future. But I think this fix is good, so I'm happy to land now and do those as followups.

@serhiipalash, can you send another PR, with a unit test for this reset bug in `StackRouter-test`, and also help add your example code to the navigation playground? (This will encourage other maintainers to test the functionality before making any big changes to the library.)

**Comment by serhiipalash** [comment]
> can you send another PR, with a unit test for this reset bug

@ericvicenti  I'll try to do it on this weekend.

**Pull request merged**
